name: Cypress CI

on:
  push:
    branches:
      - main  # Set your main branch name here
  pull_request:
    branches:
      - main  # Set your main branch name here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run cy:run  # Assuming you have a script named "cy:run" in your package.json file to run Cypress tests headlessly
