on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "spec1.cy.js"
          - "spec2.cy.js"
          # Add more spec files as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npx cypress install

      - name: Run Cypress tests and save results to JSON file
        run: |
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false
          spec_file_name=$(basename "${{ matrix.spec_file }}" .cy.js)
          missing_elements_file="cypress/fixtures/missing_elements_${spec_file_name}.json"

          # Run your Cypress test and save results to the specific missing elements file
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --env configFile=$missing_elements_file

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements_*.json
