on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "18.cy.js"
         - "19.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
         - "75.cy.js"
         - "76.cy.js"
         - "77.cy.js"
         - "78.cy.js"
         - "79.cy.js"
         - "80.cy.js"
         - "81.cy.js"
         - "82.cy.js"
         - "83.cy.js"
         - "84.cy.js"
         - "85.cy.js"
         - "86.cy.js"
         - "87.cy.js"
         - "88.cy.js"
         - "89.cy.js"
         - "90.cy.js"
         - "91.cy.js"
         - "92.cy.js"
         - "93.cy.js"
         - "94.cy.js"
         - "95.cy.js"
         - "96.cy.js"
         - "97.cy.js"
         - "98.cy.js"
         - "99.cy.js"
         - "100.cy.js"
             


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          # Wrap the Cypress run command in a try-catch block
          set +e
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27
          # Store the exit code in a variable
          EXIT_CODE=$?
          # Set back to normal behavior (exit on error)
          set -e
          # Check if the exit code is non-zero (indicating failure)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Some tests failed but continuing..."
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 240K NCTID's
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements1803.json
            cypress/fixtures/missing_elements1804.json
            cypress/fixtures/missing_elements1805.json
            cypress/fixtures/missing_elements1806.json
            cypress/fixtures/missing_elements1807.json
            cypress/fixtures/missing_elements1808.json
            cypress/fixtures/missing_elements1809.json
            cypress/fixtures/missing_elements1810.json
            cypress/fixtures/missing_elements1811.json
            cypress/fixtures/missing_elements1812.json
            cypress/fixtures/missing_elements1813.json
            cypress/fixtures/missing_elements1814.json
            cypress/fixtures/missing_elements1815.json
            cypress/fixtures/missing_elements1816.json
            cypress/fixtures/missing_elements1817.json
            cypress/fixtures/missing_elements1818.json
            cypress/fixtures/missing_elements1819.json
            cypress/fixtures/missing_elements1820.json
            cypress/fixtures/missing_elements1821.json
            cypress/fixtures/missing_elements1822.json
            cypress/fixtures/missing_elements1823.json
            cypress/fixtures/missing_elements1824.json
            cypress/fixtures/missing_elements1825.json
            cypress/fixtures/missing_elements1826.json
            cypress/fixtures/missing_elements1827.json
            cypress/fixtures/missing_elements1828.json
            cypress/fixtures/missing_elements1829.json
            cypress/fixtures/missing_elements1830.json
            cypress/fixtures/missing_elements1831.json
            cypress/fixtures/missing_elements1832.json
            cypress/fixtures/missing_elements1833.json
            cypress/fixtures/missing_elements1834.json
            cypress/fixtures/missing_elements1835.json
            cypress/fixtures/missing_elements1836.json
            cypress/fixtures/missing_elements1837.json
            cypress/fixtures/missing_elements1838.json
            cypress/fixtures/missing_elements1839.json
            cypress/fixtures/missing_elements1840.json
            cypress/fixtures/missing_elements1841.json
            cypress/fixtures/missing_elements1842.json
            cypress/fixtures/missing_elements1843.json
            cypress/fixtures/missing_elements1844.json
            cypress/fixtures/missing_elements1845.json
            cypress/fixtures/missing_elements1846.json
            cypress/fixtures/missing_elements1847.json
            cypress/fixtures/missing_elements1848.json
            cypress/fixtures/missing_elements1849.json
            cypress/fixtures/missing_elements1850.json
            cypress/fixtures/missing_elements1851.json
            cypress/fixtures/missing_elements1852.json
            cypress/fixtures/missing_elements1853.json
            cypress/fixtures/missing_elements1854.json
            cypress/fixtures/missing_elements1855.json
            cypress/fixtures/missing_elements1856.json
            cypress/fixtures/missing_elements1857.json
            cypress/fixtures/missing_elements1858.json
            cypress/fixtures/missing_elements1859.json
            cypress/fixtures/missing_elements1860.json
            cypress/fixtures/missing_elements1861.json
            cypress/fixtures/missing_elements1862.json
            cypress/fixtures/missing_elements1863.json
            cypress/fixtures/missing_elements1864.json
            cypress/fixtures/missing_elements1865.json
            cypress/fixtures/missing_elements1866.json
            cypress/fixtures/missing_elements1867.json
            cypress/fixtures/missing_elements1868.json
            cypress/fixtures/missing_elements1869.json
            cypress/fixtures/missing_elements1870.json
            cypress/fixtures/missing_elements1871.json
            cypress/fixtures/missing_elements1872.json
            cypress/fixtures/missing_elements1873.json
            cypress/fixtures/missing_elements1874.json
            cypress/fixtures/missing_elements1875.json
            cypress/fixtures/missing_elements1876.json
            cypress/fixtures/missing_elements1877.json
            cypress/fixtures/missing_elements1878.json
            cypress/fixtures/missing_elements1879.json
            cypress/fixtures/missing_elements1880.json
            cypress/fixtures/missing_elements1881.json
            cypress/fixtures/missing_elements1882.json
            cypress/fixtures/missing_elements1883.json
            cypress/fixtures/missing_elements1884.json
            cypress/fixtures/missing_elements1885.json
            cypress/fixtures/missing_elements1886.json
            cypress/fixtures/missing_elements1887.json
            cypress/fixtures/missing_elements1888.json
            cypress/fixtures/missing_elements1889.json
            cypress/fixtures/missing_elements1890.json
            cypress/fixtures/missing_elements1891.json
            cypress/fixtures/missing_elements1892.json
            cypress/fixtures/missing_elements1893.json
            cypress/fixtures/missing_elements1894.json
            cypress/fixtures/missing_elements1895.json
            cypress/fixtures/missing_elements1896.json
            cypress/fixtures/missing_elements1897.json
            cypress/fixtures/missing_elements1898.json
            cypress/fixtures/missing_elements1899.json
            cypress/fixtures/missing_elements1900.json
            cypress/fixtures/missing_elements1901.json
            cypress/fixtures/missing_elements1902.json
            cypress/fixtures/missing_elements1903.json
            cypress/fixtures/missing_elements1904.json
            cypress/fixtures/missing_elements1905.json
            cypress/fixtures/missing_elements1906.json
            cypress/fixtures/missing_elements1907.json
            cypress/fixtures/missing_elements1908.json
            cypress/fixtures/missing_elements1909.json
            cypress/fixtures/missing_elements1910.json
            cypress/fixtures/missing_elements1911.json
            cypress/fixtures/missing_elements1912.json
            cypress/fixtures/missing_elements1913.json
            cypress/fixtures/missing_elements1914.json
            cypress/fixtures/missing_elements1915.json
            cypress/fixtures/missing_elements1916.json
            cypress/fixtures/missing_elements1917.json
            cypress/fixtures/missing_elements1918.json
            cypress/fixtures/missing_elements1919.json
            cypress/fixtures/missing_elements1920.json
            cypress/fixtures/missing_elements1921.json
            cypress/fixtures/missing_elements1922.json
            cypress/fixtures/missing_elements1923.json
            cypress/fixtures/missing_elements1924.json
            cypress/fixtures/missing_elements1925.json
            cypress/fixtures/missing_elements1926.json
            cypress/fixtures/missing_elements1927.json
            cypress/fixtures/missing_elements1928.json
            cypress/fixtures/missing_elements1929.json
            cypress/fixtures/missing_elements1930.json
            cypress/fixtures/missing_elements1931.json
            cypress/fixtures/missing_elements1932.json
            cypress/fixtures/missing_elements1933.json
            cypress/fixtures/missing_elements1934.json
            cypress/fixtures/missing_elements1935.json
            cypress/fixtures/missing_elements1936.json
            cypress/fixtures/missing_elements1937.json
            cypress/fixtures/missing_elements1938.json
            cypress/fixtures/missing_elements1939.json
            cypress/fixtures/missing_elements1940.json
            cypress/fixtures/missing_elements1941.json
            cypress/fixtures/missing_elements1942.json
            cypress/fixtures/missing_elements1943.json
            cypress/fixtures/missing_elements1944.json
            cypress/fixtures/missing_elements1945.json
            cypress/fixtures/missing_elements1946.json
            cypress/fixtures/missing_elements1947.json
            cypress/fixtures/missing_elements1948.json
            cypress/fixtures/missing_elements1949.json
            cypress/fixtures/missing_elements1950.json
            cypress/fixtures/missing_elements1951.json
            cypress/fixtures/missing_elements1952.json
            cypress/fixtures/missing_elements1953.json
            cypress/fixtures/missing_elements1954.json
            cypress/fixtures/missing_elements1955.json
            cypress/fixtures/missing_elements1956.json
            cypress/fixtures/missing_elements1957.json
            cypress/fixtures/missing_elements1958.json
            cypress/fixtures/missing_elements1959.json
            cypress/fixtures/missing_elements1960.json
            cypress/fixtures/missing_elements1961.json
            cypress/fixtures/missing_elements1962.json
            cypress/fixtures/missing_elements1963.json
            cypress/fixtures/missing_elements1964.json
            cypress/fixtures/missing_elements1965.json
            cypress/fixtures/missing_elements1966.json
            cypress/fixtures/missing_elements1967.json
            cypress/fixtures/missing_elements1968.json
            cypress/fixtures/missing_elements1969.json
            cypress/fixtures/missing_elements1970.json
            cypress/fixtures/missing_elements1971.json
            cypress/fixtures/missing_elements1972.json
            cypress/fixtures/missing_elements1973.json
            cypress/fixtures/missing_elements1974.json
            cypress/fixtures/missing_elements1975.json
            cypress/fixtures/missing_elements1976.json
            cypress/fixtures/missing_elements1977.json
            cypress/fixtures/missing_elements1978.json
            cypress/fixtures/missing_elements1979.json
            cypress/fixtures/missing_elements1980.json
            cypress/fixtures/missing_elements1981.json
            cypress/fixtures/missing_elements1982.json
            cypress/fixtures/missing_elements1983.json
            cypress/fixtures/missing_elements1984.json
            cypress/fixtures/missing_elements1985.json
            cypress/fixtures/missing_elements1986.json
            cypress/fixtures/missing_elements1987.json
            cypress/fixtures/missing_elements1988.json
            cypress/fixtures/missing_elements1989.json
            cypress/fixtures/missing_elements1990.json
            cypress/fixtures/missing_elements1991.json
            cypress/fixtures/missing_elements1992.json
            cypress/fixtures/missing_elements1993.json
            cypress/fixtures/missing_elements1994.json
            cypress/fixtures/missing_elements1995.json
            cypress/fixtures/missing_elements1996.json
            cypress/fixtures/missing_elements1997.json
            cypress/fixtures/missing_elements1998.json
            cypress/fixtures/missing_elements1999.json
            cypress/fixtures/missing_elements2000.json
            cypress/fixtures/missing_elements2001.json
            cypress/fixtures/missing_elements2002.json
            continue-on-error: true
