on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "01.cy.js"
          - "02.cy.js"
          - "03.cy.js"
          - "04.cy.js"
          - "05.cy.js"
          - "06.cy.js"
          - "07.cy.js"
          - "08.cy.js"
          - "09.cy.js"
          - "10.cy.js"
          - "11.cy.js"
          - "12.cy.js"
          - "13.cy.js"
          - "14.cy.js"
          - "15.cy.js"
          - "16.cy.js"
          - "17.cy.js"
          - "18.cy.js"
          - "19.cy.js"
          - "20.cy.js"
          - "21.cy.js"
          - "22.cy.js"
          - "23.cy.js"
          - "24.cy.js"
          - "25.cy.js"
          - "26.cy.js"
          - "27.cy.js"
          - "28.cy.js"
          - "29.cy.js"
          - "30.cy.js"
          - "31.cy.js"
          - "32.cy.js"
          - "33.cy.js"
          - "34.cy.js"
          - "35.cy.js"
          - "36.cy.js"
          - "37.cy.js"
          - "38.cy.js"
          - "39.cy.js"
          - "40.cy.js"
          - "41.cy.js"
        



    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements202.json
            cypress/fixtures/missing_elements203.json
            cypress/fixtures/missing_elements204.json
            cypress/fixtures/missing_elements205.json
            cypress/fixtures/missing_elements206.json
            cypress/fixtures/missing_elements207.json
            cypress/fixtures/missing_elements208.json
            cypress/fixtures/missing_elements209.json
            cypress/fixtures/missing_elements210.json
            cypress/fixtures/missing_elements211.json
            cypress/fixtures/missing_elements212.json
            cypress/fixtures/missing_elements213.json
            cypress/fixtures/missing_elements214.json
            cypress/fixtures/missing_elements215.json
            cypress/fixtures/missing_elements216.json
            cypress/fixtures/missing_elements217.json
            cypress/fixtures/missing_elements218.json
            cypress/fixtures/missing_elements219.json
            cypress/fixtures/missing_elements220.json
            cypress/fixtures/missing_elements221.json
            cypress/fixtures/missing_elements222.json
            cypress/fixtures/missing_elements223.json
            cypress/fixtures/missing_elements224.json
            cypress/fixtures/missing_elements225.json
            cypress/fixtures/missing_elements226.json
            cypress/fixtures/missing_elements227.json
            cypress/fixtures/missing_elements228.json
            cypress/fixtures/missing_elements229.json
            cypress/fixtures/missing_elements230.json
            cypress/fixtures/missing_elements231.json
            cypress/fixtures/missing_elements232.json
            cypress/fixtures/missing_elements233.json
            cypress/fixtures/missing_elements234.json
            cypress/fixtures/missing_elements235.json
            cypress/fixtures/missing_elements236.json
            cypress/fixtures/missing_elements237.json
            cypress/fixtures/missing_elements238.json
            cypress/fixtures/missing_elements239.json
            cypress/fixtures/missing_elements240.json
            cypress/fixtures/missing_elements241.json
            cypress/fixtures/missing_elements242.json
            cypress/fixtures/missing_elements243.json
            cypress/fixtures/missing_elements244.json
            cypress/fixtures/missing_elements245.json
            cypress/fixtures/missing_elements246.json
            cypress/fixtures/missing_elements247.json
            cypress/fixtures/missing_elements248.json
            cypress/fixtures/missing_elements249.json
            cypress/fixtures/missing_elements250.json
            cypress/fixtures/missing_elements251.json
            cypress/fixtures/missing_elements252.json
            cypress/fixtures/missing_elements253.json
            cypress/fixtures/missing_elements254.json
            cypress/fixtures/missing_elements255.json
            cypress/fixtures/missing_elements256.json
            cypress/fixtures/missing_elements257.json
            cypress/fixtures/missing_elements258.json
            cypress/fixtures/missing_elements259.json
            cypress/fixtures/missing_elements260.json
            cypress/fixtures/missing_elements261.json
            cypress/fixtures/missing_elements262.json
            cypress/fixtures/missing_elements263.json
            cypress/fixtures/missing_elements264.json
            cypress/fixtures/missing_elements265.json
            cypress/fixtures/missing_elements266.json
            cypress/fixtures/missing_elements267.json
            cypress/fixtures/missing_elements268.json
            cypress/fixtures/missing_elements269.json
            cypress/fixtures/missing_elements270.json
            cypress/fixtures/missing_elements271.json
            cypress/fixtures/missing_elements272.json
            cypress/fixtures/missing_elements273.json
            cypress/fixtures/missing_elements274.json
            cypress/fixtures/missing_elements275.json
            cypress/fixtures/missing_elements276.json
            cypress/fixtures/missing_elements277.json
            cypress/fixtures/missing_elements278.json
            cypress/fixtures/missing_elements279.json
            cypress/fixtures/missing_elements280.json
            cypress/fixtures/missing_elements281.json
            cypress/fixtures/missing_elements282.json
            cypress/fixtures/missing_elements283.json
            cypress/fixtures/missing_elements284.json
            cypress/fixtures/missing_elements285.json
            cypress/fixtures/missing_elements286.json
            cypress/fixtures/missing_elements287.json
            cypress/fixtures/missing_elements288.json
            cypress/fixtures/missing_elements289.json
            cypress/fixtures/missing_elements290.json
            cypress/fixtures/missing_elements291.json
            cypress/fixtures/missing_elements292.json
            cypress/fixtures/missing_elements293.json
            cypress/fixtures/missing_elements294.json
            cypress/fixtures/missing_elements295.json
            cypress/fixtures/missing_elements296.json
            cypress/fixtures/missing_elements297.json
            cypress/fixtures/missing_elements298.json
            cypress/fixtures/missing_elements299.json
            cypress/fixtures/missing_elements300.json
            cypress/fixtures/missing_elements301.json
            cypress/fixtures/missing_elements302.json
            cypress/fixtures/missing_elements303.json
            cypress/fixtures/missing_elements304.json
            cypress/fixtures/missing_elements305.json
            cypress/fixtures/missing_elements306.json
            cypress/fixtures/missing_elements307.json
            cypress/fixtures/missing_elements308.json
            cypress/fixtures/missing_elements309.json
            cypress/fixtures/missing_elements310.json
            cypress/fixtures/missing_elements311.json
            cypress/fixtures/missing_elements312.json
            cypress/fixtures/missing_elements313.json
            cypress/fixtures/missing_elements314.json
            cypress/fixtures/missing_elements315.json
            cypress/fixtures/missing_elements316.json
            cypress/fixtures/missing_elements317.json
            cypress/fixtures/missing_elements318.json
            cypress/fixtures/missing_elements319.json
            cypress/fixtures/missing_elements320.json
            cypress/fixtures/missing_elements321.json
            cypress/fixtures/missing_elements322.json
            cypress/fixtures/missing_elements323.json
            cypress/fixtures/missing_elements324.json
            cypress/fixtures/missing_elements325.json
            cypress/fixtures/missing_elements326.json
            cypress/fixtures/missing_elements327.json
            cypress/fixtures/missing_elements328.json
            cypress/fixtures/missing_elements329.json
            cypress/fixtures/missing_elements330.json
            cypress/fixtures/missing_elements331.json
            cypress/fixtures/missing_elements332.json
            cypress/fixtures/missing_elements333.json
            cypress/fixtures/missing_elements334.json
            cypress/fixtures/missing_elements335.json
            cypress/fixtures/missing_elements336.json
            cypress/fixtures/missing_elements337.json
            cypress/fixtures/missing_elements338.json
            cypress/fixtures/missing_elements339.json
            cypress/fixtures/missing_elements340.json
            cypress/fixtures/missing_elements341.json
            cypress/fixtures/missing_elements342.json
            cypress/fixtures/missing_elements343.json
            cypress/fixtures/missing_elements344.json
            cypress/fixtures/missing_elements345.json
            cypress/fixtures/missing_elements346.json
            cypress/fixtures/missing_elements347.json
            cypress/fixtures/missing_elements348.json
            cypress/fixtures/missing_elements349.json
            cypress/fixtures/missing_elements350.json
            cypress/fixtures/missing_elements351.json
            cypress/fixtures/missing_elements352.json
            cypress/fixtures/missing_elements353.json
            cypress/fixtures/missing_elements354.json
            cypress/fixtures/missing_elements355.json
            cypress/fixtures/missing_elements356.json
            cypress/fixtures/missing_elements357.json
            cypress/fixtures/missing_elements358.json
            cypress/fixtures/missing_elements359.json
            cypress/fixtures/missing_elements360.json
            cypress/fixtures/missing_elements361.json
            cypress/fixtures/missing_elements362.json
            cypress/fixtures/missing_elements363.json
            cypress/fixtures/missing_elements364.json
            cypress/fixtures/missing_elements365.json
            cypress/fixtures/missing_elements366.json
            cypress/fixtures/missing_elements367.json
            cypress/fixtures/missing_elements368.json
            cypress/fixtures/missing_elements369.json
            cypress/fixtures/missing_elements370.json
            cypress/fixtures/missing_elements371.json
            cypress/fixtures/missing_elements372.json
            cypress/fixtures/missing_elements373.json
            cypress/fixtures/missing_elements374.json
            cypress/fixtures/missing_elements375.json
            cypress/fixtures/missing_elements376.json
            cypress/fixtures/missing_elements377.json
            cypress/fixtures/missing_elements378.json
            cypress/fixtures/missing_elements379.json
            cypress/fixtures/missing_elements380.json
            cypress/fixtures/missing_elements381.json
            cypress/fixtures/missing_elements382.json
            cypress/fixtures/missing_elements383.json
            cypress/fixtures/missing_elements384.json
            cypress/fixtures/missing_elements385.json
            cypress/fixtures/missing_elements386.json
            cypress/fixtures/missing_elements387.json
            cypress/fixtures/missing_elements388.json
            cypress/fixtures/missing_elements389.json
            cypress/fixtures/missing_elements390.json
            cypress/fixtures/missing_elements391.json
            cypress/fixtures/missing_elements392.json
            cypress/fixtures/missing_elements393.json
            cypress/fixtures/missing_elements394.json
            cypress/fixtures/missing_elements395.json
            cypress/fixtures/missing_elements396.json
            cypress/fixtures/missing_elements397.json
            cypress/fixtures/missing_elements398.json
            cypress/fixtures/missing_elements399.json
            cypress/fixtures/missing_elements400.json
            cypress/fixtures/missing_elements401.json





