on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "01.cy.js"
          - "02.cy.js"
          - "03.cy.js"
          - "04.cy.js"
          - "05.cy.js"
          - "06.cy.js"
          - "07.cy.js"
          - "08.cy.js"
          - "09.cy.js"
          - "10.cy.js"



    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements0.json
            cypress/fixtures/missing_elements1.json
            cypress/fixtures/missing_elements2.json
            cypress/fixtures/missing_elements3.json
            cypress/fixtures/missing_elements4.json
            cypress/fixtures/missing_elements5.json
            cypress/fixtures/missing_elements6.json
            cypress/fixtures/missing_elements7.json
            cypress/fixtures/missing_elements8.json
            cypress/fixtures/missing_elements9.json
            cypress/fixtures/missing_elements10.json
            cypress/fixtures/missing_elements11.json
            cypress/fixtures/missing_elements12.json
            cypress/fixtures/missing_elements13.json
            cypress/fixtures/missing_elements14.json
            cypress/fixtures/missing_elements15.json
            cypress/fixtures/missing_elements16.json
            cypress/fixtures/missing_elements17.json
            cypress/fixtures/missing_elements18.json
            cypress/fixtures/missing_elements19.json

      
          
