on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
         - "75.cy.js"
         - "76.cy.js"
         - "77.cy.js"
         - "78.cy.js"
         - "79.cy.js"
         - "80.cy.js"
         - "81.cy.js"
         - "82.cy.js"
         - "83.cy.js"
         - "84.cy.js"
         - "85.cy.js"
         - "86.cy.js"
         - "87.cy.js"
         - "88.cy.js"
         - "89.cy.js"
         - "90.cy.js"
         - "91.cy.js"
         - "92.cy.js"
         - "93.cy.js"
         - "94.cy.js"
         - "95.cy.js"
         - "96.cy.js"
         - "97.cy.js"
         - "98.cy.js"
         - "99.cy.js"
         - "100.cy.js"


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts-360-390k NCTIDs
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements2803.json
                cypress/fixtures/missing_elements2804.json
                cypress/fixtures/missing_elements2805.json
                cypress/fixtures/missing_elements2806.json
                cypress/fixtures/missing_elements2807.json
                cypress/fixtures/missing_elements2808.json
                cypress/fixtures/missing_elements2809.json
                cypress/fixtures/missing_elements2810.json
                cypress/fixtures/missing_elements2811.json
                cypress/fixtures/missing_elements2812.json
                cypress/fixtures/missing_elements2813.json
                cypress/fixtures/missing_elements2814.json
                cypress/fixtures/missing_elements2815.json
                cypress/fixtures/missing_elements2816.json
                cypress/fixtures/missing_elements2817.json
                cypress/fixtures/missing_elements2818.json
                cypress/fixtures/missing_elements2819.json
                cypress/fixtures/missing_elements2820.json
                cypress/fixtures/missing_elements2821.json
                cypress/fixtures/missing_elements2822.json
                cypress/fixtures/missing_elements2823.json
                cypress/fixtures/missing_elements2824.json
                cypress/fixtures/missing_elements2825.json
                cypress/fixtures/missing_elements2826.json
                cypress/fixtures/missing_elements2827.json
                cypress/fixtures/missing_elements2828.json
                cypress/fixtures/missing_elements2829.json
                cypress/fixtures/missing_elements2830.json
                cypress/fixtures/missing_elements2831.json
                cypress/fixtures/missing_elements2832.json
                cypress/fixtures/missing_elements2833.json
                cypress/fixtures/missing_elements2834.json
                cypress/fixtures/missing_elements2835.json
                cypress/fixtures/missing_elements2836.json
                cypress/fixtures/missing_elements2837.json
                cypress/fixtures/missing_elements2838.json
                cypress/fixtures/missing_elements2839.json
                cypress/fixtures/missing_elements2840.json
                cypress/fixtures/missing_elements2841.json
                cypress/fixtures/missing_elements2842.json
                cypress/fixtures/missing_elements2843.json
                cypress/fixtures/missing_elements2844.json
                cypress/fixtures/missing_elements2845.json
                cypress/fixtures/missing_elements2846.json
                cypress/fixtures/missing_elements2847.json
                cypress/fixtures/missing_elements2848.json
                cypress/fixtures/missing_elements2849.json
                cypress/fixtures/missing_elements2850.json
                cypress/fixtures/missing_elements2851.json
                cypress/fixtures/missing_elements2852.json
                cypress/fixtures/missing_elements2853.json
                cypress/fixtures/missing_elements2854.json
                cypress/fixtures/missing_elements2855.json
                cypress/fixtures/missing_elements2856.json
                cypress/fixtures/missing_elements2857.json
                cypress/fixtures/missing_elements2858.json
                cypress/fixtures/missing_elements2859.json
                cypress/fixtures/missing_elements2860.json
                cypress/fixtures/missing_elements2861.json
                cypress/fixtures/missing_elements2862.json
                cypress/fixtures/missing_elements2863.json
                cypress/fixtures/missing_elements2864.json
                cypress/fixtures/missing_elements2865.json
                cypress/fixtures/missing_elements2866.json
                cypress/fixtures/missing_elements2867.json
                cypress/fixtures/missing_elements2868.json
                cypress/fixtures/missing_elements2869.json
                cypress/fixtures/missing_elements2870.json
                cypress/fixtures/missing_elements2871.json
                cypress/fixtures/missing_elements2872.json
                cypress/fixtures/missing_elements2873.json
                cypress/fixtures/missing_elements2874.json
                cypress/fixtures/missing_elements2875.json
                cypress/fixtures/missing_elements2876.json
                cypress/fixtures/missing_elements2877.json
                cypress/fixtures/missing_elements2878.json
                cypress/fixtures/missing_elements2879.json
                cypress/fixtures/missing_elements2880.json
                cypress/fixtures/missing_elements2881.json
                cypress/fixtures/missing_elements2882.json
                cypress/fixtures/missing_elements2883.json
                cypress/fixtures/missing_elements2884.json
                cypress/fixtures/missing_elements2885.json
                cypress/fixtures/missing_elements2886.json
                cypress/fixtures/missing_elements2887.json
                cypress/fixtures/missing_elements2888.json
                cypress/fixtures/missing_elements2889.json
                cypress/fixtures/missing_elements2890.json
                cypress/fixtures/missing_elements2891.json
                cypress/fixtures/missing_elements2892.json
                cypress/fixtures/missing_elements2893.json
                cypress/fixtures/missing_elements2894.json
                cypress/fixtures/missing_elements2895.json
                cypress/fixtures/missing_elements2896.json
                cypress/fixtures/missing_elements2897.json
                cypress/fixtures/missing_elements2898.json
                cypress/fixtures/missing_elements2899.json
                cypress/fixtures/missing_elements2900.json
                cypress/fixtures/missing_elements2901.json
                cypress/fixtures/missing_elements2902.json
                cypress/fixtures/missing_elements2903.json
                cypress/fixtures/missing_elements2904.json
                cypress/fixtures/missing_elements2905.json
                cypress/fixtures/missing_elements2906.json
                cypress/fixtures/missing_elements2907.json
                cypress/fixtures/missing_elements2908.json
                cypress/fixtures/missing_elements2909.json
                cypress/fixtures/missing_elements2910.json
                cypress/fixtures/missing_elements2911.json
                cypress/fixtures/missing_elements2912.json
                cypress/fixtures/missing_elements2913.json
                cypress/fixtures/missing_elements2914.json
                cypress/fixtures/missing_elements2915.json
                cypress/fixtures/missing_elements2916.json
                cypress/fixtures/missing_elements2917.json
                cypress/fixtures/missing_elements2918.json
                cypress/fixtures/missing_elements2919.json
                cypress/fixtures/missing_elements2920.json
                cypress/fixtures/missing_elements2921.json
                cypress/fixtures/missing_elements2922.json
                cypress/fixtures/missing_elements2923.json
                cypress/fixtures/missing_elements2924.json
                cypress/fixtures/missing_elements2925.json
                cypress/fixtures/missing_elements2926.json
                cypress/fixtures/missing_elements2927.json
                cypress/fixtures/missing_elements2928.json
                cypress/fixtures/missing_elements2929.json
                cypress/fixtures/missing_elements2930.json
                cypress/fixtures/missing_elements2931.json
                cypress/fixtures/missing_elements2932.json
                cypress/fixtures/missing_elements2933.json
                cypress/fixtures/missing_elements2934.json
                cypress/fixtures/missing_elements2935.json
                cypress/fixtures/missing_elements2936.json
                cypress/fixtures/missing_elements2937.json
                cypress/fixtures/missing_elements2938.json
                cypress/fixtures/missing_elements2939.json
                cypress/fixtures/missing_elements2940.json
                cypress/fixtures/missing_elements2941.json
                cypress/fixtures/missing_elements2942.json
                cypress/fixtures/missing_elements2943.json
                cypress/fixtures/missing_elements2944.json
                cypress/fixtures/missing_elements2945.json
                cypress/fixtures/missing_elements2946.json
                cypress/fixtures/missing_elements2947.json
                cypress/fixtures/missing_elements2948.json
                cypress/fixtures/missing_elements2949.json
                cypress/fixtures/missing_elements2950.json
                cypress/fixtures/missing_elements2951.json
                cypress/fixtures/missing_elements2952.json
                cypress/fixtures/missing_elements2953.json
                cypress/fixtures/missing_elements2954.json
                cypress/fixtures/missing_elements2955.json
                cypress/fixtures/missing_elements2956.json
                cypress/fixtures/missing_elements2957.json
                cypress/fixtures/missing_elements2958.json
                cypress/fixtures/missing_elements2959.json
                cypress/fixtures/missing_elements2960.json
                cypress/fixtures/missing_elements2961.json
                cypress/fixtures/missing_elements2962.json
                cypress/fixtures/missing_elements2963.json
                cypress/fixtures/missing_elements2964.json
                cypress/fixtures/missing_elements2965.json
                cypress/fixtures/missing_elements2966.json
                cypress/fixtures/missing_elements2967.json
                cypress/fixtures/missing_elements2968.json
                cypress/fixtures/missing_elements2969.json
                cypress/fixtures/missing_elements2970.json
                cypress/fixtures/missing_elements2971.json
                cypress/fixtures/missing_elements2972.json
                cypress/fixtures/missing_elements2973.json
                cypress/fixtures/missing_elements2974.json
                cypress/fixtures/missing_elements2975.json
                cypress/fixtures/missing_elements2976.json
                cypress/fixtures/missing_elements2977.json
                cypress/fixtures/missing_elements2978.json
                cypress/fixtures/missing_elements2979.json
                cypress/fixtures/missing_elements2980.json
                cypress/fixtures/missing_elements2981.json
                cypress/fixtures/missing_elements2982.json
                cypress/fixtures/missing_elements2983.json
                cypress/fixtures/missing_elements2984.json
                cypress/fixtures/missing_elements2985.json
                cypress/fixtures/missing_elements2986.json
                cypress/fixtures/missing_elements2987.json
                cypress/fixtures/missing_elements2988.json
                cypress/fixtures/missing_elements2989.json
                cypress/fixtures/missing_elements2990.json
                cypress/fixtures/missing_elements2991.json
                cypress/fixtures/missing_elements2992.json
                cypress/fixtures/missing_elements2993.json
                cypress/fixtures/missing_elements2994.json
                cypress/fixtures/missing_elements2995.json
                cypress/fixtures/missing_elements2996.json
                cypress/fixtures/missing_elements2997.json
                cypress/fixtures/missing_elements2998.json
                cypress/fixtures/missing_elements2999.json
                cypress/fixtures/missing_elements3000.json
                cypress/fixtures/missing_elements3001.json
                cypress/fixtures/missing_elements3002.json


