name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install
          npx cypress run --config video=false
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/fixtures

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: cypress-results
          path: cypress-results

      - name: Display missing_elements0.json content
        run: |
          cat cypress-results/missing_elements0.json
