on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
         - "75.cy.js"
         - "76.cy.js"
         - "77.cy.js"
         - "78.cy.js"
         - "79.cy.js"
         - "80.cy.js"
         - "81.cy.js"
         - "82.cy.js"
         - "83.cy.js"
         - "84.cy.js"
         - "85.cy.js"
         - "86.cy.js"
         - "87.cy.js"
         - "88.cy.js"
         - "89.cy.js"
         - "90.cy.js"
         - "91.cy.js"
         - "92.cy.js"
         - "93.cy.js"
         - "94.cy.js"
         - "95.cy.js"
         - "96.cy.js"
         - "97.cy.js"
         - "98.cy.js"
         - "99.cy.js"
         - "100.cy.js"
             


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          # Wrap the Cypress run command in a try-catch block
          set +e
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-520573466e27
          # Store the exit code in a variable
          EXIT_CODE=$?
          # Set back to normal behavior (exit on error)
          set -e
          # Check if the exit code is non-zero (indicating failure)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Some tests failed but continuing..."
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 270K NCTID's
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements2003.json
            cypress/fixtures/missing_elements2004.json
            cypress/fixtures/missing_elements2005.json
            cypress/fixtures/missing_elements2006.json
            cypress/fixtures/missing_elements2007.json
            cypress/fixtures/missing_elements2008.json
            cypress/fixtures/missing_elements2009.json
            cypress/fixtures/missing_elements2010.json
            cypress/fixtures/missing_elements2011.json
            cypress/fixtures/missing_elements2012.json
            cypress/fixtures/missing_elements2013.json
            cypress/fixtures/missing_elements2014.json
            cypress/fixtures/missing_elements2015.json
            cypress/fixtures/missing_elements2016.json
            cypress/fixtures/missing_elements2017.json
            cypress/fixtures/missing_elements2018.json
            cypress/fixtures/missing_elements2019.json
            cypress/fixtures/missing_elements2020.json
            cypress/fixtures/missing_elements2021.json
            cypress/fixtures/missing_elements2022.json
            cypress/fixtures/missing_elements2023.json
            cypress/fixtures/missing_elements2024.json
            cypress/fixtures/missing_elements2025.json
            cypress/fixtures/missing_elements2026.json
            cypress/fixtures/missing_elements2027.json
            cypress/fixtures/missing_elements2028.json
            cypress/fixtures/missing_elements2029.json
            cypress/fixtures/missing_elements2030.json
            cypress/fixtures/missing_elements2031.json
            cypress/fixtures/missing_elements2032.json
            cypress/fixtures/missing_elements2033.json
            cypress/fixtures/missing_elements2034.json
            cypress/fixtures/missing_elements2035.json
            cypress/fixtures/missing_elements2036.json
            cypress/fixtures/missing_elements2037.json
            cypress/fixtures/missing_elements2038.json
            cypress/fixtures/missing_elements2039.json
            cypress/fixtures/missing_elements2040.json
            cypress/fixtures/missing_elements2041.json
            cypress/fixtures/missing_elements2042.json
            cypress/fixtures/missing_elements2043.json
            cypress/fixtures/missing_elements2044.json
            cypress/fixtures/missing_elements2045.json
            cypress/fixtures/missing_elements2046.json
            cypress/fixtures/missing_elements2047.json
            cypress/fixtures/missing_elements2048.json
            cypress/fixtures/missing_elements2049.json
            cypress/fixtures/missing_elements2050.json
            cypress/fixtures/missing_elements2051.json
            cypress/fixtures/missing_elements2052.json
            cypress/fixtures/missing_elements2053.json
            cypress/fixtures/missing_elements2054.json
            cypress/fixtures/missing_elements2055.json
            cypress/fixtures/missing_elements2056.json
            cypress/fixtures/missing_elements2057.json
            cypress/fixtures/missing_elements2058.json
            cypress/fixtures/missing_elements2059.json
            cypress/fixtures/missing_elements2060.json
            cypress/fixtures/missing_elements2061.json
            cypress/fixtures/missing_elements2062.json
            cypress/fixtures/missing_elements2063.json
            cypress/fixtures/missing_elements2064.json
            cypress/fixtures/missing_elements2065.json
            cypress/fixtures/missing_elements2066.json
            cypress/fixtures/missing_elements2067.json
            cypress/fixtures/missing_elements2068.json
            cypress/fixtures/missing_elements2069.json
            cypress/fixtures/missing_elements2070.json
            cypress/fixtures/missing_elements2071.json
            cypress/fixtures/missing_elements2072.json
            cypress/fixtures/missing_elements2073.json
            cypress/fixtures/missing_elements2074.json
            cypress/fixtures/missing_elements2075.json
            cypress/fixtures/missing_elements2076.json
            cypress/fixtures/missing_elements2077.json
            cypress/fixtures/missing_elements2078.json
            cypress/fixtures/missing_elements2079.json
            cypress/fixtures/missing_elements2080.json
            cypress/fixtures/missing_elements2081.json
            cypress/fixtures/missing_elements2082.json
            cypress/fixtures/missing_elements2083.json
            cypress/fixtures/missing_elements2084.json
            cypress/fixtures/missing_elements2085.json
            cypress/fixtures/missing_elements2086.json
            cypress/fixtures/missing_elements2087.json
            cypress/fixtures/missing_elements2088.json
            cypress/fixtures/missing_elements2089.json
            cypress/fixtures/missing_elements2090.json
            cypress/fixtures/missing_elements2091.json
            cypress/fixtures/missing_elements2092.json
            cypress/fixtures/missing_elements2093.json
            cypress/fixtures/missing_elements2094.json
            cypress/fixtures/missing_elements2095.json
            cypress/fixtures/missing_elements2096.json
            cypress/fixtures/missing_elements2097.json
            cypress/fixtures/missing_elements2098.json
            cypress/fixtures/missing_elements2099.json
            cypress/fixtures/missing_elements2100.json
            cypress/fixtures/missing_elements2101.json
            cypress/fixtures/missing_elements2102.json
            cypress/fixtures/missing_elements2103.json
            cypress/fixtures/missing_elements2104.json
            cypress/fixtures/missing_elements2105.json
            cypress/fixtures/missing_elements2106.json
            cypress/fixtures/missing_elements2107.json
            cypress/fixtures/missing_elements2108.json
            cypress/fixtures/missing_elements2109.json
            cypress/fixtures/missing_elements2110.json
            cypress/fixtures/missing_elements2111.json
            cypress/fixtures/missing_elements2112.json
            cypress/fixtures/missing_elements2113.json
            cypress/fixtures/missing_elements2114.json
            cypress/fixtures/missing_elements2115.json
            cypress/fixtures/missing_elements2116.json
            cypress/fixtures/missing_elements2117.json
            cypress/fixtures/missing_elements2120.json
            cypress/fixtures/missing_elements2121.json
            cypress/fixtures/missing_elements2120.json
            cypress/fixtures/missing_elements2121.json
            cypress/fixtures/missing_elements2122.json
            cypress/fixtures/missing_elements2123.json
            cypress/fixtures/missing_elements2124.json
            cypress/fixtures/missing_elements2125.json
            cypress/fixtures/missing_elements2126.json
            cypress/fixtures/missing_elements2127.json
            cypress/fixtures/missing_elements2128.json
            cypress/fixtures/missing_elements2129.json
            cypress/fixtures/missing_elements2130.json
            cypress/fixtures/missing_elements2131.json
            cypress/fixtures/missing_elements2132.json
            cypress/fixtures/missing_elements2133.json
            cypress/fixtures/missing_elements2134.json
            cypress/fixtures/missing_elements2135.json
            cypress/fixtures/missing_elements2136.json
            cypress/fixtures/missing_elements2137.json
            cypress/fixtures/missing_elements2138.json
            cypress/fixtures/missing_elements2139.json
            cypress/fixtures/missing_elements2140.json
            cypress/fixtures/missing_elements2141.json
            cypress/fixtures/missing_elements2142.json
            cypress/fixtures/missing_elements2143.json
            cypress/fixtures/missing_elements2144.json
            cypress/fixtures/missing_elements2145.json
            cypress/fixtures/missing_elements2146.json
            cypress/fixtures/missing_elements2147.json
            cypress/fixtures/missing_elements2148.json
            cypress/fixtures/missing_elements2149.json
            cypress/fixtures/missing_elements2150.json
            cypress/fixtures/missing_elements2151.json
            cypress/fixtures/missing_elements2152.json
            cypress/fixtures/missing_elements2153.json
            cypress/fixtures/missing_elements2154.json
            cypress/fixtures/missing_elements2155.json
            cypress/fixtures/missing_elements2156.json
            cypress/fixtures/missing_elements2157.json
            cypress/fixtures/missing_elements2158.json
            cypress/fixtures/missing_elements2159.json
            cypress/fixtures/missing_elements2160.json
            cypress/fixtures/missing_elements2161.json
            cypress/fixtures/missing_elements2162.json
            cypress/fixtures/missing_elements2163.json
            cypress/fixtures/missing_elements2164.json
            cypress/fixtures/missing_elements2165.json
            cypress/fixtures/missing_elements2166.json
            cypress/fixtures/missing_elements2167.json
            cypress/fixtures/missing_elements2168.json
            cypress/fixtures/missing_elements2169.json
            cypress/fixtures/missing_elements2170.json
            cypress/fixtures/missing_elements2171.json
            cypress/fixtures/missing_elements2172.json
            cypress/fixtures/missing_elements2173.json
            cypress/fixtures/missing_elements2174.json
            cypress/fixtures/missing_elements2175.json
            cypress/fixtures/missing_elements2176.json
            cypress/fixtures/missing_elements2177.json
            cypress/fixtures/missing_elements2178.json
            cypress/fixtures/missing_elements2179.json
            cypress/fixtures/missing_elements2180.json
            cypress/fixtures/missing_elements2181.json
            cypress/fixtures/missing_elements2182.json
            cypress/fixtures/missing_elements2183.json
            cypress/fixtures/missing_elements2184.json
            cypress/fixtures/missing_elements2185.json
            cypress/fixtures/missing_elements2186.json
            cypress/fixtures/missing_elements2187.json
            cypress/fixtures/missing_elements2188.json
            cypress/fixtures/missing_elements2189.json
            cypress/fixtures/missing_elements2190.json
            cypress/fixtures/missing_elements2191.json
            cypress/fixtures/missing_elements2192.json
            cypress/fixtures/missing_elements2193.json
            cypress/fixtures/missing_elements2194.json
            cypress/fixtures/missing_elements2195.json
            cypress/fixtures/missing_elements2196.json
            cypress/fixtures/missing_elements2197.json
            cypress/fixtures/missing_elements2198.json
            cypress/fixtures/missing_elements2199.json
            cypress/fixtures/missing_elements2200.json
            cypress/fixtures/missing_elements2201.json
            cypress/fixtures/missing_elements2202.json
            continue-on-error: true
