on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "18.cy.js"
         - "19.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
         - "75.cy.js"
         - "76.cy.js"
         - "77.cy.js"
         - "78.cy.js"
         - "79.cy.js"
         - "80.cy.js"
         - "81.cy.js"
         - "82.cy.js"
         - "83.cy.js"
         - "84.cy.js"
         - "85.cy.js"
         - "86.cy.js"
         - "87.cy.js"
         - "88.cy.js"
         - "89.cy.js"
         - "90.cy.js"
         - "91.cy.js"
         - "92.cy.js"
         - "93.cy.js"
         - "94.cy.js"
         - "95.cy.js"
         - "96.cy.js"
         - "97.cy.js"
         - "98.cy.js"
         - "99.cy.js"
         - "100.cy.js"
             


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          # Wrap the Cypress run command in a try-catch block
          set +e
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27
          # Store the exit code in a variable
          EXIT_CODE=$?
          # Set back to normal behavior (exit on error)
          set -e
          # Check if the exit code is non-zero (indicating failure)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Some tests failed but continuing..."
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 240K NCTID's
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements1603.json
            cypress/fixtures/missing_elements1604.json
            cypress/fixtures/missing_elements1605.json
            cypress/fixtures/missing_elements1606.json
            cypress/fixtures/missing_elements1607.json
            cypress/fixtures/missing_elements1608.json
            cypress/fixtures/missing_elements1609.json
            cypress/fixtures/missing_elements1610.json
            cypress/fixtures/missing_elements1611.json
            cypress/fixtures/missing_elements1612.json
            cypress/fixtures/missing_elements1613.json
            cypress/fixtures/missing_elements1614.json
            cypress/fixtures/missing_elements1615.json
            cypress/fixtures/missing_elements1616.json
            cypress/fixtures/missing_elements1617.json
            cypress/fixtures/missing_elements1618.json
            cypress/fixtures/missing_elements1619.json
            cypress/fixtures/missing_elements1620.json
            cypress/fixtures/missing_elements1621.json
            cypress/fixtures/missing_elements1622.json
            cypress/fixtures/missing_elements1623.json
            cypress/fixtures/missing_elements1624.json
            cypress/fixtures/missing_elements1625.json
            cypress/fixtures/missing_elements1626.json
            cypress/fixtures/missing_elements1627.json
            cypress/fixtures/missing_elements1628.json
            cypress/fixtures/missing_elements1629.json
            cypress/fixtures/missing_elements1630.json
            cypress/fixtures/missing_elements1631.json
            cypress/fixtures/missing_elements1632.json
            cypress/fixtures/missing_elements1633.json
            cypress/fixtures/missing_elements1634.json
            cypress/fixtures/missing_elements1635.json
            cypress/fixtures/missing_elements1636.json
            cypress/fixtures/missing_elements1637.json
            cypress/fixtures/missing_elements1638.json
            cypress/fixtures/missing_elements1639.json
            cypress/fixtures/missing_elements1640.json
            cypress/fixtures/missing_elements1641.json
            cypress/fixtures/missing_elements1642.json
            cypress/fixtures/missing_elements1643.json
            cypress/fixtures/missing_elements1644.json
            cypress/fixtures/missing_elements1645.json
            cypress/fixtures/missing_elements1646.json
            cypress/fixtures/missing_elements1647.json
            cypress/fixtures/missing_elements1648.json
            cypress/fixtures/missing_elements1649.json
            cypress/fixtures/missing_elements1650.json
            cypress/fixtures/missing_elements1651.json
            cypress/fixtures/missing_elements1652.json
            cypress/fixtures/missing_elements1653.json
            cypress/fixtures/missing_elements1654.json
            cypress/fixtures/missing_elements1655.json
            cypress/fixtures/missing_elements1656.json
            cypress/fixtures/missing_elements1657.json
            cypress/fixtures/missing_elements1658.json
            cypress/fixtures/missing_elements1659.json
            cypress/fixtures/missing_elements1660.json
            cypress/fixtures/missing_elements1661.json
            cypress/fixtures/missing_elements1662.json
            cypress/fixtures/missing_elements1663.json
            cypress/fixtures/missing_elements1664.json
            cypress/fixtures/missing_elements1665.json
            cypress/fixtures/missing_elements1666.json
            cypress/fixtures/missing_elements1667.json
            cypress/fixtures/missing_elements1668.json
            cypress/fixtures/missing_elements1669.json
            cypress/fixtures/missing_elements1670.json
            cypress/fixtures/missing_elements1671.json
            cypress/fixtures/missing_elements1672.json
            cypress/fixtures/missing_elements1673.json
            cypress/fixtures/missing_elements1674.json
            cypress/fixtures/missing_elements1675.json
            cypress/fixtures/missing_elements1676.json
            cypress/fixtures/missing_elements1677.json
            cypress/fixtures/missing_elements1678.json
            cypress/fixtures/missing_elements1679.json
            cypress/fixtures/missing_elements1680.json
            cypress/fixtures/missing_elements1681.json
            cypress/fixtures/missing_elements1682.json
            cypress/fixtures/missing_elements1683.json
            cypress/fixtures/missing_elements1684.json
            cypress/fixtures/missing_elements1685.json
            cypress/fixtures/missing_elements1686.json
            cypress/fixtures/missing_elements1687.json
            cypress/fixtures/missing_elements1688.json
            cypress/fixtures/missing_elements1689.json
            cypress/fixtures/missing_elements1690.json
            cypress/fixtures/missing_elements1691.json
            cypress/fixtures/missing_elements1692.json
            cypress/fixtures/missing_elements1693.json
            cypress/fixtures/missing_elements1694.json
            cypress/fixtures/missing_elements1695.json
            cypress/fixtures/missing_elements1696.json
            cypress/fixtures/missing_elements1697.json
            cypress/fixtures/missing_elements1698.json
            cypress/fixtures/missing_elements1699.json
            cypress/fixtures/missing_elements1700.json
            cypress/fixtures/missing_elements1701.json
            cypress/fixtures/missing_elements1702.json
            cypress/fixtures/missing_elements1703.json
            cypress/fixtures/missing_elements1704.json
            cypress/fixtures/missing_elements1705.json
            cypress/fixtures/missing_elements1706.json
            cypress/fixtures/missing_elements1707.json
            cypress/fixtures/missing_elements1708.json
            cypress/fixtures/missing_elements1709.json
            cypress/fixtures/missing_elements1710.json
            cypress/fixtures/missing_elements1711.json
            cypress/fixtures/missing_elements1712.json
            cypress/fixtures/missing_elements1713.json
            cypress/fixtures/missing_elements1714.json
            cypress/fixtures/missing_elements1715.json
            cypress/fixtures/missing_elements1716.json
            cypress/fixtures/missing_elements1717.json
            cypress/fixtures/missing_elements1718.json
            cypress/fixtures/missing_elements1719.json
            cypress/fixtures/missing_elements1720.json
            cypress/fixtures/missing_elements1721.json
            cypress/fixtures/missing_elements1722.json
            cypress/fixtures/missing_elements1723.json
            cypress/fixtures/missing_elements1724.json
            cypress/fixtures/missing_elements1725.json
            cypress/fixtures/missing_elements1726.json
            cypress/fixtures/missing_elements1727.json
            cypress/fixtures/missing_elements1728.json
            cypress/fixtures/missing_elements1729.json
            cypress/fixtures/missing_elements1730.json
            cypress/fixtures/missing_elements1731.json
            cypress/fixtures/missing_elements1732.json
            cypress/fixtures/missing_elements1733.json
            cypress/fixtures/missing_elements1734.json
            cypress/fixtures/missing_elements1735.json
            cypress/fixtures/missing_elements1736.json
            cypress/fixtures/missing_elements1737.json
            cypress/fixtures/missing_elements1738.json
            cypress/fixtures/missing_elements1739.json
            cypress/fixtures/missing_elements1740.json
            cypress/fixtures/missing_elements1741.json
            cypress/fixtures/missing_elements1742.json
            cypress/fixtures/missing_elements1743.json
            cypress/fixtures/missing_elements1744.json
            cypress/fixtures/missing_elements1745.json
            cypress/fixtures/missing_elements1746.json
            cypress/fixtures/missing_elements1747.json
            cypress/fixtures/missing_elements1748.json
            cypress/fixtures/missing_elements1749.json
            cypress/fixtures/missing_elements1750.json
            cypress/fixtures/missing_elements1751.json
            cypress/fixtures/missing_elements1752.json
            cypress/fixtures/missing_elements1753.json
            cypress/fixtures/missing_elements1754.json
            cypress/fixtures/missing_elements1755.json
            cypress/fixtures/missing_elements1756.json
            cypress/fixtures/missing_elements1757.json
            cypress/fixtures/missing_elements1758.json
            cypress/fixtures/missing_elements1759.json
            cypress/fixtures/missing_elements1760.json
            cypress/fixtures/missing_elements1761.json
            cypress/fixtures/missing_elements1762.json
            cypress/fixtures/missing_elements1763.json
            cypress/fixtures/missing_elements1764.json
            cypress/fixtures/missing_elements1765.json
            cypress/fixtures/missing_elements1766.json
            cypress/fixtures/missing_elements1767.json
            cypress/fixtures/missing_elements1768.json
            cypress/fixtures/missing_elements1769.json
            cypress/fixtures/missing_elements1770.json
            cypress/fixtures/missing_elements1771.json
            cypress/fixtures/missing_elements1772.json
            cypress/fixtures/missing_elements1773.json
            cypress/fixtures/missing_elements1774.json
            cypress/fixtures/missing_elements1775.json
            cypress/fixtures/missing_elements1776.json
            cypress/fixtures/missing_elements1777.json
            cypress/fixtures/missing_elements1778.json
            cypress/fixtures/missing_elements1779.json
            cypress/fixtures/missing_elements1780.json
            cypress/fixtures/missing_elements1781.json
            cypress/fixtures/missing_elements1782.json
            cypress/fixtures/missing_elements1783.json
            cypress/fixtures/missing_elements1784.json
            cypress/fixtures/missing_elements1785.json
            cypress/fixtures/missing_elements1786.json
            cypress/fixtures/missing_elements1787.json
            cypress/fixtures/missing_elements1788.json
            cypress/fixtures/missing_elements1789.json
            cypress/fixtures/missing_elements1790.json
            cypress/fixtures/missing_elements1791.json
            cypress/fixtures/missing_elements1792.json
            cypress/fixtures/missing_elements1793.json
            cypress/fixtures/missing_elements1794.json
            cypress/fixtures/missing_elements1795.json
            cypress/fixtures/missing_elements1796.json
            cypress/fixtures/missing_elements1797.json
            cypress/fixtures/missing_elements1798.json
            cypress/fixtures/missing_elements1799.json
            cypress/fixtures/missing_elements1800.json
            cypress/fixtures/missing_elements1801.json
            cypress/fixtures/missing_elements1802.json            
            continue-on-error: true
