on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "01.cy.js"
          - "02.cy.js"
          - "03.cy.js"
          - "04.cy.js"
          - "05.cy.js"
          - "06.cy.js"
          - "07.cy.js"
          - "08.cy.js"
          - "09.cy.js"
          - "10.cy.js"
          - "11.cy.js"
          - "12.cy.js"
          - "13.cy.js"
          - "14.cy.js"
          - "15.cy.js"
          - "16.cy.js"
          - "17.cy.js"
          - "18.cy.js"
          - "19.cy.js"
          - "20.cy.js"
          - "21.cy.js"
          - "22.cy.js"
          - "23.cy.js"
          - "24.cy.js"
          - "25.cy.js"
          - "26.cy.js"
          - "27.cy.js"
          - "28.cy.js"
          - "29.cy.js"
          - "30.cy.js"
          - "31.cy.js"
          - "32.cy.js"
          - "33.cy.js"
          - "34.cy.js"
          - "35.cy.js"
          - "36.cy.js"
          - "37.cy.js"
          - "38.cy.js"
          - "39.cy.js"
          - "40.cy.js"
          - "41.cy.js"
          - "42.cy.js"
          - "43.cy.js"
          - "44.cy.js"
          - "45.cy.js"
          - "46.cy.js"
          - "47.cy.js"
          - "48.cy.js"
          - "49.cy.js"
          - "50.cy.js"
          - "51.cy.js"
          - "52.cy.js"
          - "53.cy.js"
          - "54.cy.js"
          - "55.cy.js"
          - "56.cy.js"
          - "57.cy.js"
          - "58.cy.js"
          - "59.cy.js"
          - "60.cy.js"
          - "61.cy.js"
          - "62.cy.js"
          - "63.cy.js"
          - "64.cy.js"
          - "65.cy.js"
          - "66.cy.js"
          - "67.cy.js"
          - "68.cy.js"
          - "69.cy.js"
          - "70.cy.js"
          - "71.cy.js"
          - "72.cy.js"
          - "73.cy.js"
          - "74.cy.js"
          - "75.cy.js"
          - "76.cy.js"
          - "77.cy.js"
          - "78.cy.js"
          - "79.cy.js"
          - "80.cy.js"
          - "81.cy.js"
          - "82.cy.js"
          - "83.cy.js"
          - "84.cy.js"
          - "85.cy.js"
          - "86.cy.js"
          - "87.cy.js"
          - "88.cy.js"
          - "89.cy.js"
          - "90.cy.js"
          - "91.cy.js"
          - "92.cy.js"
          - "93.cy.js"
          - "94.cy.js"
          - "95.cy.js"
          - "96.cy.js"
          - "97.cy.js"
          - "98.cy.js"
          - "99.cy.js"
          - "100.cy.js"

        



    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements402.json
            cypress/fixtures/missing_elements403.json
            cypress/fixtures/missing_elements404.json
            cypress/fixtures/missing_elements405.json
            cypress/fixtures/missing_elements406.json
            cypress/fixtures/missing_elements407.json
            cypress/fixtures/missing_elements408.json
            cypress/fixtures/missing_elements409.json
            cypress/fixtures/missing_elements410.json
            cypress/fixtures/missing_elements411.json
            cypress/fixtures/missing_elements412.json
            cypress/fixtures/missing_elements413.json
            cypress/fixtures/missing_elements414.json
            cypress/fixtures/missing_elements415.json
            cypress/fixtures/missing_elements416.json
            cypress/fixtures/missing_elements417.json
            cypress/fixtures/missing_elements418.json
            cypress/fixtures/missing_elements419.json
            cypress/fixtures/missing_elements420.json
            cypress/fixtures/missing_elements421.json
            cypress/fixtures/missing_elements422.json
            cypress/fixtures/missing_elements423.json
            cypress/fixtures/missing_elements424.json
            cypress/fixtures/missing_elements425.json
            cypress/fixtures/missing_elements426.json
            cypress/fixtures/missing_elements427.json
            cypress/fixtures/missing_elements428.json
            cypress/fixtures/missing_elements429.json
            cypress/fixtures/missing_elements430.json
            cypress/fixtures/missing_elements431.json
            cypress/fixtures/missing_elements432.json
            cypress/fixtures/missing_elements433.json
            cypress/fixtures/missing_elements434.json
            cypress/fixtures/missing_elements435.json
            cypress/fixtures/missing_elements436.json
            cypress/fixtures/missing_elements437.json
            cypress/fixtures/missing_elements438.json
            cypress/fixtures/missing_elements439.json
            cypress/fixtures/missing_elements440.json
            cypress/fixtures/missing_elements441.json
            cypress/fixtures/missing_elements442.json
            cypress/fixtures/missing_elements443.json
            cypress/fixtures/missing_elements444.json
            cypress/fixtures/missing_elements445.json
            cypress/fixtures/missing_elements446.json
            cypress/fixtures/missing_elements447.json
            cypress/fixtures/missing_elements448.json
            cypress/fixtures/missing_elements449.json
            cypress/fixtures/missing_elements450.json
            cypress/fixtures/missing_elements451.json
            cypress/fixtures/missing_elements452.json
            cypress/fixtures/missing_elements453.json
            cypress/fixtures/missing_elements454.json
            cypress/fixtures/missing_elements455.json
            cypress/fixtures/missing_elements456.json
            cypress/fixtures/missing_elements457.json
            cypress/fixtures/missing_elements458.json
            cypress/fixtures/missing_elements459.json
            cypress/fixtures/missing_elements460.json
            cypress/fixtures/missing_elements461.json
            cypress/fixtures/missing_elements462.json
            cypress/fixtures/missing_elements463.json
            cypress/fixtures/missing_elements464.json
            cypress/fixtures/missing_elements465.json
            cypress/fixtures/missing_elements466.json
            cypress/fixtures/missing_elements467.json
            cypress/fixtures/missing_elements468.json
            cypress/fixtures/missing_elements469.json
            cypress/fixtures/missing_elements470.json
            cypress/fixtures/missing_elements471.json
            cypress/fixtures/missing_elements472.json
            cypress/fixtures/missing_elements473.json
            cypress/fixtures/missing_elements474.json
            cypress/fixtures/missing_elements475.json
            cypress/fixtures/missing_elements476.json
            cypress/fixtures/missing_elements477.json
            cypress/fixtures/missing_elements478.json
            cypress/fixtures/missing_elements479.json
            cypress/fixtures/missing_elements480.json
            cypress/fixtures/missing_elements481.json
            cypress/fixtures/missing_elements482.json
            cypress/fixtures/missing_elements483.json
            cypress/fixtures/missing_elements484.json
            cypress/fixtures/missing_elements485.json
            cypress/fixtures/missing_elements486.json
            cypress/fixtures/missing_elements487.json
            cypress/fixtures/missing_elements488.json
            cypress/fixtures/missing_elements489.json
            cypress/fixtures/missing_elements490.json
            cypress/fixtures/missing_elements491.json
            cypress/fixtures/missing_elements492.json
            cypress/fixtures/missing_elements493.json
            cypress/fixtures/missing_elements494.json
            cypress/fixtures/missing_elements495.json
            cypress/fixtures/missing_elements496.json
            cypress/fixtures/missing_elements497.json
            cypress/fixtures/missing_elements498.json
            cypress/fixtures/missing_elements499.json
            cypress/fixtures/missing_elements500.json
            cypress/fixtures/missing_elements501.json
            cypress/fixtures/missing_elements502.json
            cypress/fixtures/missing_elements503.json
            cypress/fixtures/missing_elements504.json
            cypress/fixtures/missing_elements505.json
            cypress/fixtures/missing_elements506.json
            cypress/fixtures/missing_elements507.json
            cypress/fixtures/missing_elements508.json
            cypress/fixtures/missing_elements509.json
            cypress/fixtures/missing_elements510.json
            cypress/fixtures/missing_elements511.json
            cypress/fixtures/missing_elements512.json
            cypress/fixtures/missing_elements513.json
            cypress/fixtures/missing_elements514.json
            cypress/fixtures/missing_elements515.json
            cypress/fixtures/missing_elements516.json
            cypress/fixtures/missing_elements517.json
            cypress/fixtures/missing_elements518.json
            cypress/fixtures/missing_elements519.json
            cypress/fixtures/missing_elements520.json
            cypress/fixtures/missing_elements521.json
            cypress/fixtures/missing_elements522.json
            cypress/fixtures/missing_elements523.json
            cypress/fixtures/missing_elements524.json
            cypress/fixtures/missing_elements525.json
            cypress/fixtures/missing_elements526.json
            cypress/fixtures/missing_elements527.json
            cypress/fixtures/missing_elements528.json
            cypress/fixtures/missing_elements529.json
            cypress/fixtures/missing_elements530.json
            cypress/fixtures/missing_elements531.json
            cypress/fixtures/missing_elements532.json
            cypress/fixtures/missing_elements533.json
            cypress/fixtures/missing_elements534.json
            cypress/fixtures/missing_elements535.json
            cypress/fixtures/missing_elements536.json
            cypress/fixtures/missing_elements537.json
            cypress/fixtures/missing_elements538.json
            cypress/fixtures/missing_elements539.json
            cypress/fixtures/missing_elements540.json
            cypress/fixtures/missing_elements541.json
            cypress/fixtures/missing_elements542.json
            cypress/fixtures/missing_elements543.json
            cypress/fixtures/missing_elements544.json
            cypress/fixtures/missing_elements545.json
            cypress/fixtures/missing_elements546.json
            cypress/fixtures/missing_elements547.json
            cypress/fixtures/missing_elements548.json
            cypress/fixtures/missing_elements549.json
            cypress/fixtures/missing_elements550.json
            cypress/fixtures/missing_elements551.json
            cypress/fixtures/missing_elements552.json
            cypress/fixtures/missing_elements553.json
            cypress/fixtures/missing_elements554.json
            cypress/fixtures/missing_elements555.json
            cypress/fixtures/missing_elements556.json
            cypress/fixtures/missing_elements557.json
            cypress/fixtures/missing_elements558.json
            cypress/fixtures/missing_elements559.json
            cypress/fixtures/missing_elements560.json
            cypress/fixtures/missing_elements561.json
            cypress/fixtures/missing_elements562.json
            cypress/fixtures/missing_elements563.json
            cypress/fixtures/missing_elements564.json
            cypress/fixtures/missing_elements565.json
            cypress/fixtures/missing_elements566.json
            cypress/fixtures/missing_elements567.json
            cypress/fixtures/missing_elements568.json
            cypress/fixtures/missing_elements569.json
            cypress/fixtures/missing_elements570.json
            cypress/fixtures/missing_elements571.json
            cypress/fixtures/missing_elements572.json
            cypress/fixtures/missing_elements573.json
            cypress/fixtures/missing_elements574.json
            cypress/fixtures/missing_elements575.json
            cypress/fixtures/missing_elements576.json
            cypress/fixtures/missing_elements577.json
            cypress/fixtures/missing_elements578.json
            cypress/fixtures/missing_elements579.json
            cypress/fixtures/missing_elements580.json
            cypress/fixtures/missing_elements581.json
            cypress/fixtures/missing_elements582.json
            cypress/fixtures/missing_elements583.json
            cypress/fixtures/missing_elements584.json
            cypress/fixtures/missing_elements585.json
            cypress/fixtures/missing_elements586.json
            cypress/fixtures/missing_elements587.json
            cypress/fixtures/missing_elements588.json
            cypress/fixtures/missing_elements589.json
            cypress/fixtures/missing_elements590.json
            cypress/fixtures/missing_elements591.json
            cypress/fixtures/missing_elements592.json
            cypress/fixtures/missing_elements593.json
            cypress/fixtures/missing_elements594.json
            cypress/fixtures/missing_elements595.json
            cypress/fixtures/missing_elements596.json
            cypress/fixtures/missing_elements597.json
            cypress/fixtures/missing_elements598.json
            cypress/fixtures/missing_elements599.json
            cypress/fixtures/missing_elements600.json
            cypress/fixtures/missing_elements601.json
            cypress/fixtures/missing_elements602.json
