on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "01.cy.js"
          - "02.cy.js"
          - "03.cy.js"
          - "04.cy.js"
          - "05.cy.js"
          - "06.cy.js"
          - "07.cy.js"
          - "08.cy.js"
          - "09.cy.js"
          - "10.cy.js"
          - "11.cy.js"
          - "12.cy.js"
          - "13.cy.js"
          - "14.cy.js"
          - "15.cy.js"
          - "16.cy.js"
          - "17.cy.js"
          - "18.cy.js"
          - "19.cy.js"
          - "20.cy.js"
          - "21.cy.js"
          - "22.cy.js"
          - "23.cy.js"
          - "24.cy.js"
          - "25.cy.js"
          - "26.cy.js"
          - "27.cy.js"
          - "28.cy.js"
          - "29.cy.js"
          - "30.cy.js"
          - "31.cy.js"
          - "32.cy.js"
          - "33.cy.js"
          - "34.cy.js"
          - "35.cy.js"
          - "36.cy.js"
          - "37.cy.js"
          - "38.cy.js"
          - "39.cy.js"
          - "40.cy.js"
          - "41.cy.js"
          - "42.cy.js"
          - "43.cy.js"
          - "44.cy.js"
          - "45.cy.js"
          - "46.cy.js"
          - "47.cy.js"
          - "48.cy.js"
          - "49.cy.js"
          - "50.cy.js"
          - "51.cy.js"
          - "52.cy.js"
          - "53.cy.js"
          - "54.cy.js"
          - "55.cy.js"
          - "56.cy.js"
          - "57.cy.js"
          - "58.cy.js"
          - "59.cy.js"
          - "60.cy.js"
          - "61.cy.js"
          - "62.cy.js"
          - "63.cy.js"
          - "64.cy.js"
          - "65.cy.js"
          - "66.cy.js"
          - "67.cy.js"
          - "68.cy.js"
          - "69.cy.js"
          - "70.cy.js"
          - "71.cy.js"
          - "72.cy.js"
          - "73.cy.js"
          - "74.cy.js"
          - "75.cy.js"
          - "76.cy.js"
          - "77.cy.js"
          - "78.cy.js"
          - "79.cy.js"
          - "80.cy.js"
          - "81.cy.js"
          - "82.cy.js"
          - "83.cy.js"
          - "84.cy.js"
          - "85.cy.js"
          - "86.cy.js"
          - "87.cy.js"
          - "88.cy.js"
          - "89.cy.js"
          - "90.cy.js"
          - "91.cy.js"
          - "92.cy.js"
          - "93.cy.js"
          - "94.cy.js"
          - "95.cy.js"
          - "96.cy.js"
          - "97.cy.js"
          - "98.cy.js"
          - "99.cy.js"
          - "100.cy.js"

        



    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements602.json
                        cypress/fixtures/missing_elements603.json
                        cypress/fixtures/missing_elements604.json
                        cypress/fixtures/missing_elements605.json
                        cypress/fixtures/missing_elements606.json
                        cypress/fixtures/missing_elements607.json
                        cypress/fixtures/missing_elements608.json
                        cypress/fixtures/missing_elements609.json
                        cypress/fixtures/missing_elements610.json
                        cypress/fixtures/missing_elements611.json
                        cypress/fixtures/missing_elements612.json
                        cypress/fixtures/missing_elements613.json
                        cypress/fixtures/missing_elements614.json
                        cypress/fixtures/missing_elements615.json
                        cypress/fixtures/missing_elements616.json
                        cypress/fixtures/missing_elements617.json
                        cypress/fixtures/missing_elements618.json
                        cypress/fixtures/missing_elements619.json
                        cypress/fixtures/missing_elements620.json
                        cypress/fixtures/missing_elements621.json
                        cypress/fixtures/missing_elements622.json
                        cypress/fixtures/missing_elements623.json
                        cypress/fixtures/missing_elements624.json
                        cypress/fixtures/missing_elements625.json
                        cypress/fixtures/missing_elements626.json
                        cypress/fixtures/missing_elements627.json
                        cypress/fixtures/missing_elements628.json
                        cypress/fixtures/missing_elements629.json
                        cypress/fixtures/missing_elements630.json
                        cypress/fixtures/missing_elements631.json
                        cypress/fixtures/missing_elements632.json
                        cypress/fixtures/missing_elements633.json
                        cypress/fixtures/missing_elements634.json
                        cypress/fixtures/missing_elements635.json
                        cypress/fixtures/missing_elements636.json
                        cypress/fixtures/missing_elements637.json
                        cypress/fixtures/missing_elements638.json
                        cypress/fixtures/missing_elements639.json
                        cypress/fixtures/missing_elements640.json
                        cypress/fixtures/missing_elements641.json
                        cypress/fixtures/missing_elements642.json
                        cypress/fixtures/missing_elements643.json
                        cypress/fixtures/missing_elements644.json
                        cypress/fixtures/missing_elements645.json
                        cypress/fixtures/missing_elements646.json
                        cypress/fixtures/missing_elements647.json
                        cypress/fixtures/missing_elements648.json
                        cypress/fixtures/missing_elements649.json
                        cypress/fixtures/missing_elements650.json
                        cypress/fixtures/missing_elements651.json
                        cypress/fixtures/missing_elements652.json
                        cypress/fixtures/missing_elements653.json
                        cypress/fixtures/missing_elements654.json
                        cypress/fixtures/missing_elements655.json
                        cypress/fixtures/missing_elements656.json
                        cypress/fixtures/missing_elements657.json
                        cypress/fixtures/missing_elements658.json
                        cypress/fixtures/missing_elements659.json
                        cypress/fixtures/missing_elements660.json
                        cypress/fixtures/missing_elements661.json
                        cypress/fixtures/missing_elements662.json
                        cypress/fixtures/missing_elements663.json
                        cypress/fixtures/missing_elements664.json
                        cypress/fixtures/missing_elements665.json
                        cypress/fixtures/missing_elements666.json
                        cypress/fixtures/missing_elements667.json
                        cypress/fixtures/missing_elements668.json
                        cypress/fixtures/missing_elements669.json
                        cypress/fixtures/missing_elements670.json
                        cypress/fixtures/missing_elements671.json
                        cypress/fixtures/missing_elements672.json
                        cypress/fixtures/missing_elements673.json
                        cypress/fixtures/missing_elements674.json
                        cypress/fixtures/missing_elements675.json
                        cypress/fixtures/missing_elements676.json
                        cypress/fixtures/missing_elements677.json
                        cypress/fixtures/missing_elements678.json
                        cypress/fixtures/missing_elements679.json
                        cypress/fixtures/missing_elements680.json
                        cypress/fixtures/missing_elements681.json
                        cypress/fixtures/missing_elements682.json
                        cypress/fixtures/missing_elements683.json
                        cypress/fixtures/missing_elements684.json
                        cypress/fixtures/missing_elements685.json
                        cypress/fixtures/missing_elements686.json
                        cypress/fixtures/missing_elements687.json
                        cypress/fixtures/missing_elements688.json
                        cypress/fixtures/missing_elements689.json
                        cypress/fixtures/missing_elements690.json
                        cypress/fixtures/missing_elements691.json
                        cypress/fixtures/missing_elements692.json
                        cypress/fixtures/missing_elements693.json
                        cypress/fixtures/missing_elements694.json
                        cypress/fixtures/missing_elements695.json
                        cypress/fixtures/missing_elements696.json
                        cypress/fixtures/missing_elements697.json
                        cypress/fixtures/missing_elements698.json
                        cypress/fixtures/missing_elements699.json
                        cypress/fixtures/missing_elements700.json
                        cypress/fixtures/missing_elements701.json
                        cypress/fixtures/missing_elements702.json
                        cypress/fixtures/missing_elements703.json
                        cypress/fixtures/missing_elements704.json
                        cypress/fixtures/missing_elements705.json
                        cypress/fixtures/missing_elements706.json
                        cypress/fixtures/missing_elements707.json
                        cypress/fixtures/missing_elements708.json
                        cypress/fixtures/missing_elements709.json
                        cypress/fixtures/missing_elements710.json
                        cypress/fixtures/missing_elements711.json
                        cypress/fixtures/missing_elements712.json
                        cypress/fixtures/missing_elements713.json
                        cypress/fixtures/missing_elements714.json
                        cypress/fixtures/missing_elements715.json
                        cypress/fixtures/missing_elements716.json
                        cypress/fixtures/missing_elements717.json
                        cypress/fixtures/missing_elements718.json
                        cypress/fixtures/missing_elements719.json
                        cypress/fixtures/missing_elements720.json
                        cypress/fixtures/missing_elements721.json
                        cypress/fixtures/missing_elements722.json
                        cypress/fixtures/missing_elements723.json
                        cypress/fixtures/missing_elements724.json
                        cypress/fixtures/missing_elements725.json
                        cypress/fixtures/missing_elements726.json
                        cypress/fixtures/missing_elements727.json
                        cypress/fixtures/missing_elements728.json
                        cypress/fixtures/missing_elements729.json
                        cypress/fixtures/missing_elements730.json
                        cypress/fixtures/missing_elements731.json
                        cypress/fixtures/missing_elements732.json
                        cypress/fixtures/missing_elements733.json
                        cypress/fixtures/missing_elements734.json
                        cypress/fixtures/missing_elements735.json
                        cypress/fixtures/missing_elements736.json
                        cypress/fixtures/missing_elements737.json
                        cypress/fixtures/missing_elements738.json
                        cypress/fixtures/missing_elements739.json
                        cypress/fixtures/missing_elements740.json
                        cypress/fixtures/missing_elements741.json
                        cypress/fixtures/missing_elements742.json
                        cypress/fixtures/missing_elements743.json
                        cypress/fixtures/missing_elements744.json
                        cypress/fixtures/missing_elements745.json
                        cypress/fixtures/missing_elements746.json
                        cypress/fixtures/missing_elements747.json
                        cypress/fixtures/missing_elements748.json
                        cypress/fixtures/missing_elements749.json
                        cypress/fixtures/missing_elements750.json
                        cypress/fixtures/missing_elements751.json
                        cypress/fixtures/missing_elements752.json
                        cypress/fixtures/missing_elements753.json
                        cypress/fixtures/missing_elements754.json
                        cypress/fixtures/missing_elements755.json
                        cypress/fixtures/missing_elements756.json
                        cypress/fixtures/missing_elements757.json
                        cypress/fixtures/missing_elements758.json
                        cypress/fixtures/missing_elements759.json
                        cypress/fixtures/missing_elements760.json
                        cypress/fixtures/missing_elements761.json
                        cypress/fixtures/missing_elements762.json
                        cypress/fixtures/missing_elements763.json
                        cypress/fixtures/missing_elements764.json
                        cypress/fixtures/missing_elements765.json
                        cypress/fixtures/missing_elements766.json
                        cypress/fixtures/missing_elements767.json
                        cypress/fixtures/missing_elements768.json
                        cypress/fixtures/missing_elements769.json
                        cypress/fixtures/missing_elements770.json
                        cypress/fixtures/missing_elements771.json
                        cypress/fixtures/missing_elements772.json
                        cypress/fixtures/missing_elements773.json
                        cypress/fixtures/missing_elements774.json
                        cypress/fixtures/missing_elements775.json
                        cypress/fixtures/missing_elements776.json
                        cypress/fixtures/missing_elements777.json
                        cypress/fixtures/missing_elements778.json
                        cypress/fixtures/missing_elements779.json
                        cypress/fixtures/missing_elements780.json
                        cypress/fixtures/missing_elements781.json
                        cypress/fixtures/missing_elements782.json
                        cypress/fixtures/missing_elements783.json
                        cypress/fixtures/missing_elements784.json
                        cypress/fixtures/missing_elements785.json
                        cypress/fixtures/missing_elements786.json
                        cypress/fixtures/missing_elements787.json
                        cypress/fixtures/missing_elements788.json
                        cypress/fixtures/missing_elements789.json
                        cypress/fixtures/missing_elements790.json
                        cypress/fixtures/missing_elements791.json
                        cypress/fixtures/missing_elements792.json
                        cypress/fixtures/missing_elements793.json
                        cypress/fixtures/missing_elements794.json
                        cypress/fixtures/missing_elements795.json
                        cypress/fixtures/missing_elements796.json
                        cypress/fixtures/missing_elements797.json
                        cypress/fixtures/missing_elements798.json
                        cypress/fixtures/missing_elements799.json
                        cypress/fixtures/missing_elements800.json
                        cypress/fixtures/missing_elements801.json
                        cypress/fixtures/missing_elements802.json
                        