on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "01.cy.js"
          - "02.cy.js"
          - "03.cy.js"
          - "04.cy.js"
          - "05.cy.js"
          - "06.cy.js"
          - "07.cy.js"
          - "08.cy.js"
          - "09.cy.js"
          - "10.cy.js"
          - "11.cy.js"
          - "12.cy.js"
          - "13.cy.js"
          - "14.cy.js"
          - "15.cy.js"
          - "16.cy.js"
          - "17.cy.js"
          - "18.cy.js"
          - "19.cy.js"
          - "20.cy.js"
          - "21.cy.js"
          - "22.cy.js"
          - "23.cy.js"
          - "24.cy.js"
          - "25.cy.js"
          - "26.cy.js"
          - "27.cy.js"
          - "28.cy.js"
          - "29.cy.js"
          - "30.cy.js"
          - "31.cy.js"
          - "32.cy.js"
          - "33.cy.js"
          - "34.cy.js"
          - "35.cy.js"
          - "36.cy.js"
          - "37.cy.js"
          - "38.cy.js"
          - "39.cy.js"
          - "40.cy.js"
          - "41.cy.js"
          - "42.cy.js"
          - "43.cy.js"
          - "44.cy.js"
          - "45.cy.js"
          - "46.cy.js"
          - "47.cy.js"
          - "48.cy.js"
          - "49.cy.js"
          - "50.cy.js"
          - "51.cy.js"
          - "52.cy.js"
          - "53.cy.js"
          - "54.cy.js"
          - "55.cy.js"
          - "56.cy.js"
          - "57.cy.js"
          - "58.cy.js"
          - "59.cy.js"
          - "60.cy.js"
          - "61.cy.js"
          - "62.cy.js"
          - "63.cy.js"
          - "64.cy.js"
          - "65.cy.js"
          - "66.cy.js"
          - "67.cy.js"
          - "68.cy.js"
          - "69.cy.js"
          - "70.cy.js"
          - "71.cy.js"
          - "72.cy.js"
          - "73.cy.js"
          - "74.cy.js"
          - "75.cy.js"
          - "76.cy.js"
          - "77.cy.js"
          - "78.cy.js"
          - "79.cy.js"
          - "80.cy.js"
          - "81.cy.js"
          - "82.cy.js"
          - "83.cy.js"
          - "84.cy.js"
          - "85.cy.js"
          - "86.cy.js"
          - "87.cy.js"
          - "88.cy.js"
          - "89.cy.js"
          - "90.cy.js"
          - "91.cy.js"
          - "92.cy.js"
          - "93.cy.js"
          - "94.cy.js"
          - "95.cy.js"
          - "96.cy.js"
          - "97.cy.js"
          - "98.cy.js"
          - "99.cy.js"
          - "100.cy.js"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 180K NCTID's
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements1203.json
                      cypress/fixtures/missing_elements1204.json
                      cypress/fixtures/missing_elements1205.json
                      cypress/fixtures/missing_elements1206.json
                      cypress/fixtures/missing_elements1207.json
                      cypress/fixtures/missing_elements1208.json
                      cypress/fixtures/missing_elements1209.json
                      cypress/fixtures/missing_elements1210.json
                      cypress/fixtures/missing_elements1211.json
                      cypress/fixtures/missing_elements1212.json
                      cypress/fixtures/missing_elements1213.json
                      cypress/fixtures/missing_elements1214.json
                      cypress/fixtures/missing_elements1215.json
                      cypress/fixtures/missing_elements1216.json
                      cypress/fixtures/missing_elements1217.json
                      cypress/fixtures/missing_elements1218.json
                      cypress/fixtures/missing_elements1219.json
                      cypress/fixtures/missing_elements1220.json
                      cypress/fixtures/missing_elements1221.json
                      cypress/fixtures/missing_elements1222.json
                      cypress/fixtures/missing_elements1223.json
                      cypress/fixtures/missing_elements1224.json
                      cypress/fixtures/missing_elements1225.json
                      cypress/fixtures/missing_elements1226.json
                      cypress/fixtures/missing_elements1227.json
                      cypress/fixtures/missing_elements1228.json
                      cypress/fixtures/missing_elements1229.json
                      cypress/fixtures/missing_elements1230.json
                      cypress/fixtures/missing_elements1231.json
                      cypress/fixtures/missing_elements1232.json
                      cypress/fixtures/missing_elements1233.json
                      cypress/fixtures/missing_elements1234.json
                      cypress/fixtures/missing_elements1235.json
                      cypress/fixtures/missing_elements1236.json
                      cypress/fixtures/missing_elements1237.json
                      cypress/fixtures/missing_elements1238.json
                      cypress/fixtures/missing_elements1239.json
                      cypress/fixtures/missing_elements1240.json
                      cypress/fixtures/missing_elements1241.json
                      cypress/fixtures/missing_elements1242.json
                      cypress/fixtures/missing_elements1243.json
                      cypress/fixtures/missing_elements1244.json
                      cypress/fixtures/missing_elements1245.json
                      cypress/fixtures/missing_elements1246.json
                      cypress/fixtures/missing_elements1247.json
                      cypress/fixtures/missing_elements1248.json
                      cypress/fixtures/missing_elements1249.json
                      cypress/fixtures/missing_elements1250.json
                      cypress/fixtures/missing_elements1251.json
                      cypress/fixtures/missing_elements1252.json
                      cypress/fixtures/missing_elements1253.json
                      cypress/fixtures/missing_elements1254.json
                      cypress/fixtures/missing_elements1255.json
                      cypress/fixtures/missing_elements1256.json
                      cypress/fixtures/missing_elements1257.json
                      cypress/fixtures/missing_elements1258.json
                      cypress/fixtures/missing_elements1259.json
                      cypress/fixtures/missing_elements1260.json
                      cypress/fixtures/missing_elements1261.json
                      cypress/fixtures/missing_elements1262.json
                      cypress/fixtures/missing_elements1263.json
                      cypress/fixtures/missing_elements1264.json
                      cypress/fixtures/missing_elements1265.json
                      cypress/fixtures/missing_elements1266.json
                      cypress/fixtures/missing_elements1267.json
                      cypress/fixtures/missing_elements1268.json
                      cypress/fixtures/missing_elements1269.json
                      cypress/fixtures/missing_elements1270.json
                      cypress/fixtures/missing_elements1271.json
                      cypress/fixtures/missing_elements1272.json
                      cypress/fixtures/missing_elements1273.json
                      cypress/fixtures/missing_elements1274.json
                      cypress/fixtures/missing_elements1275.json
                      cypress/fixtures/missing_elements1276.json
                      cypress/fixtures/missing_elements1277.json
                      cypress/fixtures/missing_elements1278.json
                      cypress/fixtures/missing_elements1279.json
                      cypress/fixtures/missing_elements1280.json
                      cypress/fixtures/missing_elements1281.json
                      cypress/fixtures/missing_elements1282.json
                      cypress/fixtures/missing_elements1283.json
                      cypress/fixtures/missing_elements1284.json
                      cypress/fixtures/missing_elements1285.json
                      cypress/fixtures/missing_elements1286.json
                      cypress/fixtures/missing_elements1287.json
                      cypress/fixtures/missing_elements1288.json
                      cypress/fixtures/missing_elements1289.json
                      cypress/fixtures/missing_elements1290.json
                      cypress/fixtures/missing_elements1291.json
                      cypress/fixtures/missing_elements1292.json
                      cypress/fixtures/missing_elements1293.json
                      cypress/fixtures/missing_elements1294.json
                      cypress/fixtures/missing_elements1295.json
                      cypress/fixtures/missing_elements1296.json
                      cypress/fixtures/missing_elements1297.json
                      cypress/fixtures/missing_elements1298.json
                      cypress/fixtures/missing_elements1299.json
                      cypress/fixtures/missing_elements1300.json
                      cypress/fixtures/missing_elements1301.json
                      cypress/fixtures/missing_elements1302.json
                      cypress/fixtures/missing_elements1303.json
                      cypress/fixtures/missing_elements1304.json
                      cypress/fixtures/missing_elements1305.json
                      cypress/fixtures/missing_elements1306.json
                      cypress/fixtures/missing_elements1307.json
                      cypress/fixtures/missing_elements1308.json
                      cypress/fixtures/missing_elements1309.json
                      cypress/fixtures/missing_elements1310.json
                      cypress/fixtures/missing_elements1311.json
                      cypress/fixtures/missing_elements1312.json
                      cypress/fixtures/missing_elements1313.json
                      cypress/fixtures/missing_elements1314.json
                      cypress/fixtures/missing_elements1315.json
                      cypress/fixtures/missing_elements1316.json
                      cypress/fixtures/missing_elements1317.json
                      cypress/fixtures/missing_elements1318.json
                      cypress/fixtures/missing_elements1319.json
                      cypress/fixtures/missing_elements1320.json
                      cypress/fixtures/missing_elements1321.json
                      cypress/fixtures/missing_elements1322.json
                      cypress/fixtures/missing_elements1323.json
                      cypress/fixtures/missing_elements1324.json
                      cypress/fixtures/missing_elements1325.json
                      cypress/fixtures/missing_elements1326.json
                      cypress/fixtures/missing_elements1327.json
                      cypress/fixtures/missing_elements1328.json
                      cypress/fixtures/missing_elements1329.json
                      cypress/fixtures/missing_elements1330.json
                      cypress/fixtures/missing_elements1331.json
                      cypress/fixtures/missing_elements1332.json
                      cypress/fixtures/missing_elements1333.json
                      cypress/fixtures/missing_elements1334.json
                      cypress/fixtures/missing_elements1335.json
                      cypress/fixtures/missing_elements1336.json
                      cypress/fixtures/missing_elements1337.json
                      cypress/fixtures/missing_elements1338.json
                      cypress/fixtures/missing_elements1339.json
                      cypress/fixtures/missing_elements1340.json
                      cypress/fixtures/missing_elements1341.json
                      cypress/fixtures/missing_elements1342.json
                      cypress/fixtures/missing_elements1343.json
                      cypress/fixtures/missing_elements1344.json
                      cypress/fixtures/missing_elements1345.json
                      cypress/fixtures/missing_elements1346.json
                      cypress/fixtures/missing_elements1347.json
                      cypress/fixtures/missing_elements1348.json
                      cypress/fixtures/missing_elements1349.json
                      cypress/fixtures/missing_elements1350.json
                      cypress/fixtures/missing_elements1351.json
                      cypress/fixtures/missing_elements1352.json
                      cypress/fixtures/missing_elements1353.json
                      cypress/fixtures/missing_elements1354.json
                      cypress/fixtures/missing_elements1355.json
                      cypress/fixtures/missing_elements1356.json
                      cypress/fixtures/missing_elements1357.json
                      cypress/fixtures/missing_elements1358.json
                      cypress/fixtures/missing_elements1359.json
                      cypress/fixtures/missing_elements1360.json
                      cypress/fixtures/missing_elements1361.json
                      cypress/fixtures/missing_elements1362.json
                      cypress/fixtures/missing_elements1363.json
                      cypress/fixtures/missing_elements1364.json
                      cypress/fixtures/missing_elements1365.json
                      cypress/fixtures/missing_elements1366.json
                      cypress/fixtures/missing_elements1367.json
                      cypress/fixtures/missing_elements1368.json
                      cypress/fixtures/missing_elements1369.json
                      cypress/fixtures/missing_elements1370.json
                      cypress/fixtures/missing_elements1371.json
                      cypress/fixtures/missing_elements1372.json
                      cypress/fixtures/missing_elements1373.json
                      cypress/fixtures/missing_elements1374.json
                      cypress/fixtures/missing_elements1375.json
                      cypress/fixtures/missing_elements1376.json
                      cypress/fixtures/missing_elements1377.json
                      cypress/fixtures/missing_elements1378.json
                      cypress/fixtures/missing_elements1379.json
                      cypress/fixtures/missing_elements1380.json
                      cypress/fixtures/missing_elements1381.json
                      cypress/fixtures/missing_elements1382.json
                      cypress/fixtures/missing_elements1383.json
                      cypress/fixtures/missing_elements1384.json
                      cypress/fixtures/missing_elements1385.json
                      cypress/fixtures/missing_elements1386.json
                      cypress/fixtures/missing_elements1387.json
                      cypress/fixtures/missing_elements1388.json
                      cypress/fixtures/missing_elements1389.json
                      cypress/fixtures/missing_elements1390.json
                      cypress/fixtures/missing_elements1391.json
                      cypress/fixtures/missing_elements1392.json
                      cypress/fixtures/missing_elements1393.json
                      cypress/fixtures/missing_elements1394.json
                      cypress/fixtures/missing_elements1395.json
                      cypress/fixtures/missing_elements1396.json
                      cypress/fixtures/missing_elements1397.json
                      cypress/fixtures/missing_elements1398.json
                      cypress/fixtures/missing_elements1399.json
                      cypress/fixtures/missing_elements1400.json
                      cypress/fixtures/missing_elements1401.json
                      cypress/fixtures/missing_elements1402.json
