on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "devidedjson.cy.js"
          - "devidedjson1.cy.js"
          - "devidedjson2.cy.js"
          - "devidedjson3.cy.js"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements.json
            cypress/fixtures/missing_elements1.json
            cypress/fixtures/missing_elements2.json
            cypress/fixtures/missing_elements3.json
