name: Cypress Tests

on:
  push:
    branches:
      - main # Change this to the branch you want to run tests on
  pull_request:
    branches:
      - main # Change this to the branch you want to run tests on

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Find Cypress spec files
        id: find-specs
        run: |
          echo "::set-output name=specs::$(find . -type f -name '*.spec.js' -o -name '*.spec.ts' -print0 | tr '\n' ',' | sed 's/,$//')"
        shell: bash

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          for spec in $(echo "${{ steps.find-specs.outputs.specs }}" | tr "," "\n")
          do
            npx cypress run --spec "$spec" --config video=false &
          done
          wait
