name: Cypress Tests

on:
  push:
    branches:
      - main # Change this to the branch you want to run tests on
  pull_request:
    branches:
      - main # Change this to the branch you want to run tests on

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "devidedjson.cy.js"
          - "devidedjson1.cy.js"
          # Add more spec files as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false # Disable video recording to save storage space

      - name: Create emptydata.json file
        run: |
          echo '{}' > cypress/fixtures/emptydata.json

      - name: Display emptydata.json content
        run: |
          cat cypress/fixtures/emptydata.json

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: emptydata # The name of the artifact
          path: cypress/fixtures/emptydata.json
