name: Cypress Tests

on:
  push:
    branches:
      - main # Change this to the branch you want to run tests on
  pull_request:
    branches:
      - main # Change this to the branch you want to run tests on

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      # ... Previous steps remain unchanged ...

      - name: Display emptydata0.json content
        run: |
          cat cypress/fixtures/emptydata0.json

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: emptydata # The name of the artifact
          path: cypress/fixtures/emptydata0.json
