on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
         - "75.cy.js"
         - "76.cy.js"
         - "77.cy.js"
         - "78.cy.js"
         - "79.cy.js"
         - "80.cy.js"
         - "81.cy.js"
         - "82.cy.js"
         - "83.cy.js"
         - "84.cy.js"
         - "85.cy.js"
         - "86.cy.js"
         - "87.cy.js"
         - "88.cy.js"
         - "89.cy.js"
         - "90.cy.js"
         - "91.cy.js"
         - "92.cy.js"
         - "93.cy.js"
         - "94.cy.js"
         - "95.cy.js"
         - "96.cy.js"
         - "97.cy.js"
         - "98.cy.js"
         - "99.cy.js"
         - "100.cy.js"
             


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          # Wrap the Cypress run command in a try-catch block
          set +e
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27
          # Store the exit code in a variable
          EXIT_CODE=$?
          # Set back to normal behavior (exit on error)
          set -e
          # Check if the exit code is non-zero (indicating failure)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Some tests failed but continuing..."
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 270K NCTID's
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements2203.json
            cypress/fixtures/missing_elements2204.json
            cypress/fixtures/missing_elements2205.json
            cypress/fixtures/missing_elements2206.json
            cypress/fixtures/missing_elements2207.json
            cypress/fixtures/missing_elements2208.json
            cypress/fixtures/missing_elements2209.json
            cypress/fixtures/missing_elements2210.json
            cypress/fixtures/missing_elements2211.json
            cypress/fixtures/missing_elements2212.json
            cypress/fixtures/missing_elements2213.json
            cypress/fixtures/missing_elements2214.json
            cypress/fixtures/missing_elements2215.json
            cypress/fixtures/missing_elements2216.json
            cypress/fixtures/missing_elements2217.json
            cypress/fixtures/missing_elements2218.json
            cypress/fixtures/missing_elements2219.json
            cypress/fixtures/missing_elements2220.json
            cypress/fixtures/missing_elements2221.json
            cypress/fixtures/missing_elements2222.json
            cypress/fixtures/missing_elements2223.json
            cypress/fixtures/missing_elements2224.json
            cypress/fixtures/missing_elements2225.json
            cypress/fixtures/missing_elements2226.json
            cypress/fixtures/missing_elements2227.json
            cypress/fixtures/missing_elements2228.json
            cypress/fixtures/missing_elements2229.json
            cypress/fixtures/missing_elements2230.json
            cypress/fixtures/missing_elements2231.json
            cypress/fixtures/missing_elements2232.json
            cypress/fixtures/missing_elements2233.json
            cypress/fixtures/missing_elements2234.json
            cypress/fixtures/missing_elements2235.json
            cypress/fixtures/missing_elements2236.json
            cypress/fixtures/missing_elements2237.json
            cypress/fixtures/missing_elements2238.json
            cypress/fixtures/missing_elements2239.json
            cypress/fixtures/missing_elements2240.json
            cypress/fixtures/missing_elements2241.json
            cypress/fixtures/missing_elements2242.json
            cypress/fixtures/missing_elements2243.json
            cypress/fixtures/missing_elements2244.json
            cypress/fixtures/missing_elements2245.json
            cypress/fixtures/missing_elements2246.json
            cypress/fixtures/missing_elements2247.json
            cypress/fixtures/missing_elements2248.json
            cypress/fixtures/missing_elements2249.json
            cypress/fixtures/missing_elements2250.json
            cypress/fixtures/missing_elements2251.json
            cypress/fixtures/missing_elements2252.json
            cypress/fixtures/missing_elements2253.json
            cypress/fixtures/missing_elements2254.json
            cypress/fixtures/missing_elements2255.json
            cypress/fixtures/missing_elements2256.json
            cypress/fixtures/missing_elements2257.json
            cypress/fixtures/missing_elements2258.json
            cypress/fixtures/missing_elements2259.json
            cypress/fixtures/missing_elements2260.json
            cypress/fixtures/missing_elements2261.json
            cypress/fixtures/missing_elements2262.json
            cypress/fixtures/missing_elements2263.json
            cypress/fixtures/missing_elements2264.json
            cypress/fixtures/missing_elements2265.json
            cypress/fixtures/missing_elements2266.json
            cypress/fixtures/missing_elements2267.json
            cypress/fixtures/missing_elements2268.json
            cypress/fixtures/missing_elements2269.json
            cypress/fixtures/missing_elements2270.json
            cypress/fixtures/missing_elements2271.json
            cypress/fixtures/missing_elements2272.json
            cypress/fixtures/missing_elements2273.json
            cypress/fixtures/missing_elements2274.json
            cypress/fixtures/missing_elements2275.json
            cypress/fixtures/missing_elements2276.json
            cypress/fixtures/missing_elements2277.json
            cypress/fixtures/missing_elements2278.json
            cypress/fixtures/missing_elements2279.json
            cypress/fixtures/missing_elements2280.json
            cypress/fixtures/missing_elements2281.json
            cypress/fixtures/missing_elements2282.json
            cypress/fixtures/missing_elements2283.json
            cypress/fixtures/missing_elements2284.json
            cypress/fixtures/missing_elements2285.json
            cypress/fixtures/missing_elements2286.json
            cypress/fixtures/missing_elements2287.json
            cypress/fixtures/missing_elements2288.json
            cypress/fixtures/missing_elements2289.json
            cypress/fixtures/missing_elements2290.json
            cypress/fixtures/missing_elements2291.json
            cypress/fixtures/missing_elements2292.json
            cypress/fixtures/missing_elements2293.json
            cypress/fixtures/missing_elements2294.json
            cypress/fixtures/missing_elements2295.json
            cypress/fixtures/missing_elements2296.json
            cypress/fixtures/missing_elements2297.json
            cypress/fixtures/missing_elements2298.json
            cypress/fixtures/missing_elements2299.json
            cypress/fixtures/missing_elements2300.json
            cypress/fixtures/missing_elements2301.json
            cypress/fixtures/missing_elements2302.json
            cypress/fixtures/missing_elements2303.json
            cypress/fixtures/missing_elements2304.json
            cypress/fixtures/missing_elements2305.json
            cypress/fixtures/missing_elements2306.json
            cypress/fixtures/missing_elements2307.json
            cypress/fixtures/missing_elements2308.json
            cypress/fixtures/missing_elements2309.json
            cypress/fixtures/missing_elements2310.json
            cypress/fixtures/missing_elements2311.json
            cypress/fixtures/missing_elements2312.json
            cypress/fixtures/missing_elements2313.json
            cypress/fixtures/missing_elements2314.json
            cypress/fixtures/missing_elements2315.json
            cypress/fixtures/missing_elements2316.json
            cypress/fixtures/missing_elements2317.json
            cypress/fixtures/missing_elements2318.json
            cypress/fixtures/missing_elements2319.json
            cypress/fixtures/missing_elements2320.json
            cypress/fixtures/missing_elements2321.json
            cypress/fixtures/missing_elements2322.json
            cypress/fixtures/missing_elements2323.json
            cypress/fixtures/missing_elements2324.json
            cypress/fixtures/missing_elements2325.json
            cypress/fixtures/missing_elements2326.json
            cypress/fixtures/missing_elements2327.json
            cypress/fixtures/missing_elements2328.json
            cypress/fixtures/missing_elements2329.json
            cypress/fixtures/missing_elements2330.json
            cypress/fixtures/missing_elements2331.json
            cypress/fixtures/missing_elements2332.json
            cypress/fixtures/missing_elements2333.json
            cypress/fixtures/missing_elements2334.json
            cypress/fixtures/missing_elements2335.json
            cypress/fixtures/missing_elements2336.json
            cypress/fixtures/missing_elements2337.json
            cypress/fixtures/missing_elements2338.json
            cypress/fixtures/missing_elements2339.json
            cypress/fixtures/missing_elements2340.json
            cypress/fixtures/missing_elements2341.json
            cypress/fixtures/missing_elements2342.json
            cypress/fixtures/missing_elements2343.json
            cypress/fixtures/missing_elements2344.json
            cypress/fixtures/missing_elements2345.json
            cypress/fixtures/missing_elements2346.json
            cypress/fixtures/missing_elements2347.json
            cypress/fixtures/missing_elements2348.json
            cypress/fixtures/missing_elements2349.json
            cypress/fixtures/missing_elements2350.json
            cypress/fixtures/missing_elements2351.json
            cypress/fixtures/missing_elements2352.json
            cypress/fixtures/missing_elements2353.json
            cypress/fixtures/missing_elements2354.json
            cypress/fixtures/missing_elements2355.json
            cypress/fixtures/missing_elements2356.json
            cypress/fixtures/missing_elements2357.json
            cypress/fixtures/missing_elements2358.json
            cypress/fixtures/missing_elements2359.json
            cypress/fixtures/missing_elements2360.json
            cypress/fixtures/missing_elements2361.json
            cypress/fixtures/missing_elements2362.json
            cypress/fixtures/missing_elements2363.json
            cypress/fixtures/missing_elements2364.json
            cypress/fixtures/missing_elements2365.json
            cypress/fixtures/missing_elements2366.json
            cypress/fixtures/missing_elements2367.json
            cypress/fixtures/missing_elements2368.json
            cypress/fixtures/missing_elements2369.json
            cypress/fixtures/missing_elements2370.json
            cypress/fixtures/missing_elements2371.json
            cypress/fixtures/missing_elements2372.json
            cypress/fixtures/missing_elements2373.json
            cypress/fixtures/missing_elements2374.json
            cypress/fixtures/missing_elements2375.json
            cypress/fixtures/missing_elements2376.json
            cypress/fixtures/missing_elements2377.json
            cypress/fixtures/missing_elements2378.json
            cypress/fixtures/missing_elements2379.json
            cypress/fixtures/missing_elements2380.json
            cypress/fixtures/missing_elements2381.json
            cypress/fixtures/missing_elements2382.json
            cypress/fixtures/missing_elements2383.json
            cypress/fixtures/missing_elements2384.json
            cypress/fixtures/missing_elements2385.json
            cypress/fixtures/missing_elements2386.json
            cypress/fixtures/missing_elements2387.json
            cypress/fixtures/missing_elements2388.json
            cypress/fixtures/missing_elements2389.json
            cypress/fixtures/missing_elements2390.json
            cypress/fixtures/missing_elements2391.json
            cypress/fixtures/missing_elements2392.json
            cypress/fixtures/missing_elements2393.json
            cypress/fixtures/missing_elements2394.json
            cypress/fixtures/missing_elements2395.json
            cypress/fixtures/missing_elements2396.json
            cypress/fixtures/missing_elements2397.json
            cypress/fixtures/missing_elements2398.json
            cypress/fixtures/missing_elements2399.json
            cypress/fixtures/missing_elements2400.json
            cypress/fixtures/missing_elements2401.json
            cypress/fixtures/missing_elements2402.json
             continue-on-error: true
