on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "01.cy.js"
          - "02.cy.js"
          - "03.cy.js"
          - "04.cy.js"
          - "05.cy.js"
          - "06.cy.js"
          - "07.cy.js"
          - "08.cy.js"
          - "09.cy.js"
          - "10.cy.js"
          - "11.cy.js"
          - "12.cy.js"
          - "13.cy.js"
          - "14.cy.js"
          - "15.cy.js"
          - "16.cy.js"
          - "17.cy.js"
          - "18.cy.js"
          - "19.cy.js"
          - "20.cy.js"
          - "21.cy.js"
          - "22.cy.js"
          - "23.cy.js"
          - "24.cy.js"
          - "25.cy.js"
          - "26.cy.js"
          - "27.cy.js"
          - "28.cy.js"
          - "29.cy.js"
          - "30.cy.js"
          - "31.cy.js"
          - "32.cy.js"
          - "33.cy.js"
          - "34.cy.js"
          - "35.cy.js"
          - "36.cy.js"
          - "37.cy.js"
          - "38.cy.js"
          - "39.cy.js"
          - "40.cy.js"
          - "41.cy.js"
          - "42.cy.js"
          - "43.cy.js"
          - "44.cy.js"
          - "45.cy.js"
          - "46.cy.js"
          - "47.cy.js"
          - "48.cy.js"
          - "49.cy.js"
          - "50.cy.js"
          - "51.cy.js"
          - "52.cy.js"
          - "53.cy.js"
          - "54.cy.js"
          - "55.cy.js"
          - "56.cy.js"
          - "57.cy.js"
          - "58.cy.js"
          - "59.cy.js"
          - "60.cy.js"
          - "61.cy.js"
          - "62.cy.js"
          - "63.cy.js"
          - "64.cy.js"
          - "65.cy.js"
          - "66.cy.js"
          - "67.cy.js"
          - "68.cy.js"
          - "69.cy.js"
          - "70.cy.js"
          - "71.cy.js"
          - "72.cy.js"
          - "73.cy.js"
          - "74.cy.js"
          - "75.cy.js"
          - "76.cy.js"
          - "77.cy.js"
          - "78.cy.js"
          - "79.cy.js"
          - "80.cy.js"
          - "81.cy.js"
          - "82.cy.js"
          - "83.cy.js"
          - "84.cy.js"
          - "85.cy.js"
          - "86.cy.js"
          - "87.cy.js"
          - "88.cy.js"
          - "89.cy.js"
          - "90.cy.js"
          - "91.cy.js"
          - "92.cy.js"
          - "93.cy.js"
          - "94.cy.js"
          - "95.cy.js"
          - "96.cy.js"
          - "97.cy.js"
          - "98.cy.js"
          - "99.cy.js"
          - "100.cy.js"
        



    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements0.json
            cypress/fixtures/missing_elements1.json
            cypress/fixtures/missing_elements2.json
            cypress/fixtures/missing_elements3.json
            cypress/fixtures/missing_elements4.json
            cypress/fixtures/missing_elements5.json
            cypress/fixtures/missing_elements6.json
            cypress/fixtures/missing_elements7.json
            cypress/fixtures/missing_elements8.json
            cypress/fixtures/missing_elements9.json
            cypress/fixtures/missing_elements10.json
            cypress/fixtures/missing_elements11.json
            cypress/fixtures/missing_elements12.json
            cypress/fixtures/missing_elements13.json
            cypress/fixtures/missing_elements14.json
            cypress/fixtures/missing_elements15.json
            cypress/fixtures/missing_elements16.json
            cypress/fixtures/missing_elements17.json
            cypress/fixtures/missing_elements18.json
            cypress/fixtures/missing_elements19.json
            cypress/fixtures/missing_elements20.json
            cypress/fixtures/missing_elements21.json
            cypress/fixtures/missing_elements22.json
            cypress/fixtures/missing_elements23.json
            cypress/fixtures/missing_elements24.json
            cypress/fixtures/missing_elements25.json
            cypress/fixtures/missing_elements26.json
            cypress/fixtures/missing_elements27.json
            cypress/fixtures/missing_elements28.json
            cypress/fixtures/missing_elements29.json
            cypress/fixtures/missing_elements30.json
            cypress/fixtures/missing_elements31.json
            cypress/fixtures/missing_elements32.json
            cypress/fixtures/missing_elements33.json
            cypress/fixtures/missing_elements34.json
            cypress/fixtures/missing_elements35.json
            cypress/fixtures/missing_elements36.json
            cypress/fixtures/missing_elements37.json
            cypress/fixtures/missing_elements38.json
            cypress/fixtures/missing_elements39.json
            cypress/fixtures/missing_elements40.json
            cypress/fixtures/missing_elements41.json
            cypress/fixtures/missing_elements42.json
            cypress/fixtures/missing_elements43.json
            cypress/fixtures/missing_elements44.json
            cypress/fixtures/missing_elements45.json
            cypress/fixtures/missing_elements46.json
            cypress/fixtures/missing_elements47.json
            cypress/fixtures/missing_elements48.json
            cypress/fixtures/missing_elements49.json
            cypress/fixtures/missing_elements50.json
            cypress/fixtures/missing_elements51.json
            cypress/fixtures/missing_elements52.json
            cypress/fixtures/missing_elements53.json
            cypress/fixtures/missing_elements54.json
            cypress/fixtures/missing_elements55.json
            cypress/fixtures/missing_elements56.json
            cypress/fixtures/missing_elements57.json
            cypress/fixtures/missing_elements58.json
            cypress/fixtures/missing_elements59.json
            cypress/fixtures/missing_elements60.json
            cypress/fixtures/missing_elements61.json
            cypress/fixtures/missing_elements62.json
            cypress/fixtures/missing_elements63.json
            cypress/fixtures/missing_elements64.json
            cypress/fixtures/missing_elements65.json
            cypress/fixtures/missing_elements66.json
            cypress/fixtures/missing_elements67.json
            cypress/fixtures/missing_elements68.json
            cypress/fixtures/missing_elements69.json
            cypress/fixtures/missing_elements70.json
            cypress/fixtures/missing_elements71.json
            cypress/fixtures/missing_elements72.json
            cypress/fixtures/missing_elements73.json
            cypress/fixtures/missing_elements74.json
            cypress/fixtures/missing_elements75.json
            cypress/fixtures/missing_elements76.json
            cypress/fixtures/missing_elements77.json
            cypress/fixtures/missing_elements78.json
            cypress/fixtures/missing_elements79.json
            cypress/fixtures/missing_elements80.json
            cypress/fixtures/missing_elements81.json
            cypress/fixtures/missing_elements82.json
            cypress/fixtures/missing_elements83.json
            cypress/fixtures/missing_elements84.json
            cypress/fixtures/missing_elements85.json
            cypress/fixtures/missing_elements86.json
            cypress/fixtures/missing_elements87.json
            cypress/fixtures/missing_elements88.json
            cypress/fixtures/missing_elements89.json
            cypress/fixtures/missing_elements90.json
            cypress/fixtures/missing_elements91.json
            cypress/fixtures/missing_elements92.json
            cypress/fixtures/missing_elements93.json
            cypress/fixtures/missing_elements94.json
            cypress/fixtures/missing_elements95.json
            cypress/fixtures/missing_elements96.json
            cypress/fixtures/missing_elements97.json
            cypress/fixtures/missing_elements98.json
            cypress/fixtures/missing_elements99.json
            cypress/fixtures/missing_elements100.json
            cypress/fixtures/missing_elements101.json
            cypress/fixtures/missing_elements102.json
            cypress/fixtures/missing_elements103.json
            cypress/fixtures/missing_elements104.json
            cypress/fixtures/missing_elements105.json
            cypress/fixtures/missing_elements106.json
            cypress/fixtures/missing_elements107.json
            cypress/fixtures/missing_elements108.json
            cypress/fixtures/missing_elements109.json
            cypress/fixtures/missing_elements110.json
            cypress/fixtures/missing_elements111.json
            cypress/fixtures/missing_elements112.json
            cypress/fixtures/missing_elements113.json
            cypress/fixtures/missing_elements114.json
            cypress/fixtures/missing_elements115.json
            cypress/fixtures/missing_elements116.json
            cypress/fixtures/missing_elements117.json
            cypress/fixtures/missing_elements118.json
            cypress/fixtures/missing_elements119.json
            cypress/fixtures/missing_elements120.json
            cypress/fixtures/missing_elements121.json
            cypress/fixtures/missing_elements122.json
            cypress/fixtures/missing_elements123.json
            cypress/fixtures/missing_elements124.json
            cypress/fixtures/missing_elements125.json
            cypress/fixtures/missing_elements126.json
            cypress/fixtures/missing_elements127.json
            cypress/fixtures/missing_elements128.json
            cypress/fixtures/missing_elements129.json
            cypress/fixtures/missing_elements130.json
            cypress/fixtures/missing_elements131.json
            cypress/fixtures/missing_elements132.json
            cypress/fixtures/missing_elements133.json
            cypress/fixtures/missing_elements134.json
            cypress/fixtures/missing_elements135.json
            cypress/fixtures/missing_elements136.json
            cypress/fixtures/missing_elements137.json
            cypress/fixtures/missing_elements138.json
            cypress/fixtures/missing_elements139.json
            cypress/fixtures/missing_elements140.json
            cypress/fixtures/missing_elements141.json
            cypress/fixtures/missing_elements142.json
            cypress/fixtures/missing_elements143.json
            cypress/fixtures/missing_elements144.json
            cypress/fixtures/missing_elements145.json
            cypress/fixtures/missing_elements146.json
            cypress/fixtures/missing_elements147.json
            cypress/fixtures/missing_elements148.json
            cypress/fixtures/missing_elements149.json
            cypress/fixtures/missing_elements150.json
            cypress/fixtures/missing_elements151.json
            cypress/fixtures/missing_elements152.json
            cypress/fixtures/missing_elements153.json
            cypress/fixtures/missing_elements154.json
            cypress/fixtures/missing_elements155.json
            cypress/fixtures/missing_elements156.json
            cypress/fixtures/missing_elements157.json
            cypress/fixtures/missing_elements158.json
            cypress/fixtures/missing_elements159.json
            cypress/fixtures/missing_elements160.json
            cypress/fixtures/missing_elements161.json
            cypress/fixtures/missing_elements162.json
            cypress/fixtures/missing_elements163.json
            cypress/fixtures/missing_elements164.json
            cypress/fixtures/missing_elements165.json
            cypress/fixtures/missing_elements166.json
            cypress/fixtures/missing_elements167.json
            cypress/fixtures/missing_elements168.json
            cypress/fixtures/missing_elements169.json
            cypress/fixtures/missing_elements170.json
            cypress/fixtures/missing_elements171.json
            cypress/fixtures/missing_elements172.json
            cypress/fixtures/missing_elements173.json
            cypress/fixtures/missing_elements174.json
            cypress/fixtures/missing_elements175.json
            cypress/fixtures/missing_elements176.json
            cypress/fixtures/missing_elements177.json
            cypress/fixtures/missing_elements178.json
            cypress/fixtures/missing_elements179.json
            cypress/fixtures/missing_elements180.json
            cypress/fixtures/missing_elements181.json
            cypress/fixtures/missing_elements182.json
            cypress/fixtures/missing_elements183.json
            cypress/fixtures/missing_elements184.json
            cypress/fixtures/missing_elements185.json
            cypress/fixtures/missing_elements186.json
            cypress/fixtures/missing_elements187.json
            cypress/fixtures/missing_elements188.json
            cypress/fixtures/missing_elements189.json
            cypress/fixtures/missing_elements190.json
            cypress/fixtures/missing_elements191.json
            cypress/fixtures/missing_elements192.json
            cypress/fixtures/missing_elements193.json
            cypress/fixtures/missing_elements194.json
            cypress/fixtures/missing_elements195.json
            cypress/fixtures/missing_elements196.json
            cypress/fixtures/missing_elements197.json
            cypress/fixtures/missing_elements198.json
            cypress/fixtures/missing_elements199.json
            cypress/fixtures/missing_elements220.json
            cypress/fixtures/missing_elements201.json





