on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "18.cy.js"
         - "19.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
         - "75.cy.js"
         - "76.cy.js"
         - "77.cy.js"
         - "78.cy.js"
         - "79.cy.js"
         - "80.cy.js"
         - "81.cy.js"
         - "82.cy.js"
         - "83.cy.js"
         - "84.cy.js"
         - "85.cy.js"
         - "86.cy.js"
         - "87.cy.js"
         - "88.cy.js"
         - "89.cy.js"
         - "90.cy.js"
         - "91.cy.js"
         - "92.cy.js"
         - "93.cy.js"
         - "94.cy.js"
         - "95.cy.js"
         - "96.cy.js"
         - "97.cy.js"
         - "98.cy.js"
         - "99.cy.js"
         - "100.cy.js"
             


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          # Wrap the Cypress run command in a try-catch block
          set +e
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27
          # Store the exit code in a variable
          EXIT_CODE=$?
          # Set back to normal behavior (exit on error)
          set -e
          # Check if the exit code is non-zero (indicating failure)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Some tests failed but continuing..."
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 210K NCTID's
          path: |
            cypress/videos
            cypress/screenshots
                  cypress/fixtures/missing_elements1403.json
                  cypress/fixtures/missing_elements1404.json
                  cypress/fixtures/missing_elements1405.json
                  cypress/fixtures/missing_elements1406.json
                  cypress/fixtures/missing_elements1407.json
                  cypress/fixtures/missing_elements1408.json
                  cypress/fixtures/missing_elements1409.json
                  cypress/fixtures/missing_elements1410.json
                  cypress/fixtures/missing_elements1411.json
                  cypress/fixtures/missing_elements1412.json
                  cypress/fixtures/missing_elements1413.json
                  cypress/fixtures/missing_elements1414.json
                  cypress/fixtures/missing_elements1415.json
                  cypress/fixtures/missing_elements1416.json
                  cypress/fixtures/missing_elements1417.json
                  cypress/fixtures/missing_elements1418.json
                  cypress/fixtures/missing_elements1419.json
                  cypress/fixtures/missing_elements1420.json
                  cypress/fixtures/missing_elements1421.json
                  cypress/fixtures/missing_elements1422.json
                  cypress/fixtures/missing_elements1423.json
                  cypress/fixtures/missing_elements1424.json
                  cypress/fixtures/missing_elements1425.json
                  cypress/fixtures/missing_elements1426.json
                  cypress/fixtures/missing_elements1427.json
                  cypress/fixtures/missing_elements1428.json
                  cypress/fixtures/missing_elements1429.json
                  cypress/fixtures/missing_elements1430.json
                  cypress/fixtures/missing_elements1431.json
                  cypress/fixtures/missing_elements1432.json
                  cypress/fixtures/missing_elements1433.json
                  cypress/fixtures/missing_elements1434.json
                  cypress/fixtures/missing_elements1435.json
                  cypress/fixtures/missing_elements1436.json
                  cypress/fixtures/missing_elements1437.json
                  cypress/fixtures/missing_elements1438.json
                  cypress/fixtures/missing_elements1439.json
                  cypress/fixtures/missing_elements1440.json
                  cypress/fixtures/missing_elements1441.json
                  cypress/fixtures/missing_elements1442.json
                  cypress/fixtures/missing_elements1443.json
                  cypress/fixtures/missing_elements1444.json
                  cypress/fixtures/missing_elements1445.json
                  cypress/fixtures/missing_elements1446.json
                  cypress/fixtures/missing_elements1447.json
                  cypress/fixtures/missing_elements1448.json
                  cypress/fixtures/missing_elements1449.json
                  cypress/fixtures/missing_elements1450.json
                  cypress/fixtures/missing_elements1451.json
                  cypress/fixtures/missing_elements1452.json
                  cypress/fixtures/missing_elements1453.json
                  cypress/fixtures/missing_elements1454.json
                  cypress/fixtures/missing_elements1455.json
                  cypress/fixtures/missing_elements1456.json
                  cypress/fixtures/missing_elements1457.json
                  cypress/fixtures/missing_elements1458.json
                  cypress/fixtures/missing_elements1459.json
                  cypress/fixtures/missing_elements1460.json
                  cypress/fixtures/missing_elements1461.json
                  cypress/fixtures/missing_elements1462.json
                  cypress/fixtures/missing_elements1463.json
                  cypress/fixtures/missing_elements1464.json
                  cypress/fixtures/missing_elements1465.json
                  cypress/fixtures/missing_elements1466.json
                  cypress/fixtures/missing_elements1467.json
                  cypress/fixtures/missing_elements1468.json
                  cypress/fixtures/missing_elements1469.json
                  cypress/fixtures/missing_elements1470.json
                  cypress/fixtures/missing_elements1471.json
                  cypress/fixtures/missing_elements1472.json
                  cypress/fixtures/missing_elements1473.json
                  cypress/fixtures/missing_elements1474.json
                  cypress/fixtures/missing_elements1475.json
                  cypress/fixtures/missing_elements1476.json
                  cypress/fixtures/missing_elements1477.json
                  cypress/fixtures/missing_elements1478.json
                  cypress/fixtures/missing_elements1479.json
                  cypress/fixtures/missing_elements1480.json
                  cypress/fixtures/missing_elements1481.json
                  cypress/fixtures/missing_elements1482.json
                  cypress/fixtures/missing_elements1483.json
                  cypress/fixtures/missing_elements1484.json
                  cypress/fixtures/missing_elements1485.json
                  cypress/fixtures/missing_elements1486.json
                  cypress/fixtures/missing_elements1487.json
                  cypress/fixtures/missing_elements1488.json
                  cypress/fixtures/missing_elements1489.json
                  cypress/fixtures/missing_elements1490.json
                  cypress/fixtures/missing_elements1491.json
                  cypress/fixtures/missing_elements1492.json
                  cypress/fixtures/missing_elements1493.json
                  cypress/fixtures/missing_elements1494.json
                  cypress/fixtures/missing_elements1495.json
                  cypress/fixtures/missing_elements1496.json
                  cypress/fixtures/missing_elements1497.json
                  cypress/fixtures/missing_elements1498.json
                  cypress/fixtures/missing_elements1499.json
                  cypress/fixtures/missing_elements1500.json
                  cypress/fixtures/missing_elements1501.json
                  cypress/fixtures/missing_elements1502.json
                  cypress/fixtures/missing_elements1503.json
                  cypress/fixtures/missing_elements1504.json
                  cypress/fixtures/missing_elements1505.json
                  cypress/fixtures/missing_elements1506.json
                  cypress/fixtures/missing_elements1507.json
                  cypress/fixtures/missing_elements1508.json
                  cypress/fixtures/missing_elements1509.json
                  cypress/fixtures/missing_elements1510.json
                  cypress/fixtures/missing_elements1511.json
                  cypress/fixtures/missing_elements1512.json
                  cypress/fixtures/missing_elements1513.json
                  cypress/fixtures/missing_elements1514.json
                  cypress/fixtures/missing_elements1515.json
                  cypress/fixtures/missing_elements1516.json
                  cypress/fixtures/missing_elements1517.json
                  cypress/fixtures/missing_elements1518.json
                  cypress/fixtures/missing_elements1519.json
                  cypress/fixtures/missing_elements1520.json
                  cypress/fixtures/missing_elements1521.json
                  cypress/fixtures/missing_elements1522.json
                  cypress/fixtures/missing_elements1523.json
                  cypress/fixtures/missing_elements1524.json
                  cypress/fixtures/missing_elements1525.json
                  cypress/fixtures/missing_elements1526.json
                  cypress/fixtures/missing_elements1527.json
                  cypress/fixtures/missing_elements1528.json
                  cypress/fixtures/missing_elements1529.json
                  cypress/fixtures/missing_elements1530.json
                  cypress/fixtures/missing_elements1531.json
                  cypress/fixtures/missing_elements1532.json
                  cypress/fixtures/missing_elements1533.json
                  cypress/fixtures/missing_elements1534.json
                  cypress/fixtures/missing_elements1535.json
                  cypress/fixtures/missing_elements1536.json
                  cypress/fixtures/missing_elements1537.json
                  cypress/fixtures/missing_elements1538.json
                  cypress/fixtures/missing_elements1539.json
                  cypress/fixtures/missing_elements1540.json
                  cypress/fixtures/missing_elements1541.json
                  cypress/fixtures/missing_elements1542.json
                  cypress/fixtures/missing_elements1543.json
                  cypress/fixtures/missing_elements1544.json
                  cypress/fixtures/missing_elements1545.json
                  cypress/fixtures/missing_elements1546.json
                  cypress/fixtures/missing_elements1547.json
                  cypress/fixtures/missing_elements1548.json
                  cypress/fixtures/missing_elements1549.json
                  cypress/fixtures/missing_elements1550.json
                  cypress/fixtures/missing_elements1551.json
                  cypress/fixtures/missing_elements1552.json
                  cypress/fixtures/missing_elements1553.json
                  cypress/fixtures/missing_elements1554.json
                  cypress/fixtures/missing_elements1555.json
                  cypress/fixtures/missing_elements1556.json
                  cypress/fixtures/missing_elements1557.json
                  cypress/fixtures/missing_elements1558.json
                  cypress/fixtures/missing_elements1559.json
                  cypress/fixtures/missing_elements1560.json
                  cypress/fixtures/missing_elements1561.json
                  cypress/fixtures/missing_elements1562.json
                  cypress/fixtures/missing_elements1563.json
                  cypress/fixtures/missing_elements1564.json
                  cypress/fixtures/missing_elements1565.json
                  cypress/fixtures/missing_elements1566.json
                  cypress/fixtures/missing_elements1567.json
                  cypress/fixtures/missing_elements1568.json
                  cypress/fixtures/missing_elements1569.json
                  cypress/fixtures/missing_elements1570.json
                  cypress/fixtures/missing_elements1571.json
                  cypress/fixtures/missing_elements1572.json
                  cypress/fixtures/missing_elements1573.json
                  cypress/fixtures/missing_elements1574.json
                  cypress/fixtures/missing_elements1575.json
                  cypress/fixtures/missing_elements1576.json
                  cypress/fixtures/missing_elements1577.json
                  cypress/fixtures/missing_elements1578.json
                  cypress/fixtures/missing_elements1579.json
                  cypress/fixtures/missing_elements1580.json
                  cypress/fixtures/missing_elements1581.json
                  cypress/fixtures/missing_elements1582.json
                  cypress/fixtures/missing_elements1583.json
                  cypress/fixtures/missing_elements1584.json
                  cypress/fixtures/missing_elements1585.json
                  cypress/fixtures/missing_elements1586.json
                  cypress/fixtures/missing_elements1587.json
                  cypress/fixtures/missing_elements1588.json
                  cypress/fixtures/missing_elements1589.json
                  cypress/fixtures/missing_elements1590.json
                  cypress/fixtures/missing_elements1591.json
                  cypress/fixtures/missing_elements1592.json
                  cypress/fixtures/missing_elements1593.json
                  cypress/fixtures/missing_elements1594.json
                  cypress/fixtures/missing_elements1595.json
                  cypress/fixtures/missing_elements1596.json
                  cypress/fixtures/missing_elements1597.json
                  cypress/fixtures/missing_elements1598.json
                  cypress/fixtures/missing_elements1599.json
                  cypress/fixtures/missing_elements1600.json
                  cypress/fixtures/missing_elements1601.json
                  cypress/fixtures/missing_elements1602.json
                  continue-on-error: true
