on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
          - "01.cy.js"
          - "02.cy.js"
          - "03.cy.js"
          - "04.cy.js"
          - "05.cy.js"
          - "06.cy.js"
          - "07.cy.js"
          - "08.cy.js"
          - "09.cy.js"
          - "10.cy.js"
          - "11.cy.js"
          - "12.cy.js"
          - "13.cy.js"
          - "14.cy.js"
          - "15.cy.js"
          - "16.cy.js"
          - "17.cy.js"
          - "18.cy.js"
          - "19.cy.js"
          - "20.cy.js"
          - "21.cy.js"
          - "22.cy.js"
          - "23.cy.js"
          - "24.cy.js"
          - "25.cy.js"
          - "26.cy.js"
          - "27.cy.js"
          - "28.cy.js"
          - "29.cy.js"
          - "30.cy.js"
          - "31.cy.js"
          - "32.cy.js"
          - "33.cy.js"
          - "34.cy.js"
          - "35.cy.js"
          - "36.cy.js"
          - "37.cy.js"
          - "38.cy.js"
          - "39.cy.js"
          - "40.cy.js"
          - "41.cy.js"
          - "42.cy.js"
          - "43.cy.js"
          - "44.cy.js"
          - "45.cy.js"
          - "46.cy.js"
          - "47.cy.js"
          - "48.cy.js"
          - "49.cy.js"
          - "50.cy.js"
          - "51.cy.js"
          - "52.cy.js"
          - "53.cy.js"
          - "54.cy.js"
          - "55.cy.js"
          - "56.cy.js"
          - "57.cy.js"
          - "58.cy.js"
          - "59.cy.js"
          - "60.cy.js"
          - "61.cy.js"
          - "62.cy.js"
          - "63.cy.js"
          - "64.cy.js"
          - "65.cy.js"
          - "66.cy.js"
          - "67.cy.js"
          - "68.cy.js"
          - "69.cy.js"
          - "70.cy.js"
          - "71.cy.js"
          - "72.cy.js"
          - "73.cy.js"
          - "74.cy.js"
          - "75.cy.js"
          - "76.cy.js"
          - "77.cy.js"
          - "78.cy.js"
          - "79.cy.js"
          - "80.cy.js"
          - "81.cy.js"
          - "82.cy.js"
          - "83.cy.js"
          - "84.cy.js"
          - "85.cy.js"
          - "86.cy.js"
          - "87.cy.js"
          - "88.cy.js"
          - "89.cy.js"
          - "90.cy.js"
          - "91.cy.js"
          - "92.cy.js"
          - "93.cy.js"
          - "94.cy.js"
          - "95.cy.js"
          - "96.cy.js"
          - "97.cy.js"
          - "98.cy.js"
          - "99.cy.js"
          - "100.cy.js"

        



    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements803.json
            cypress/fixtures/missing_elements804.json
            cypress/fixtures/missing_elements805.json
            cypress/fixtures/missing_elements806.json
            cypress/fixtures/missing_elements807.json
            cypress/fixtures/missing_elements808.json
            cypress/fixtures/missing_elements809.json
            cypress/fixtures/missing_elements810.json
            cypress/fixtures/missing_elements811.json
            cypress/fixtures/missing_elements812.json
            cypress/fixtures/missing_elements813.json
            cypress/fixtures/missing_elements814.json
            cypress/fixtures/missing_elements815.json
            cypress/fixtures/missing_elements816.json
            cypress/fixtures/missing_elements817.json
            cypress/fixtures/missing_elements818.json
            cypress/fixtures/missing_elements819.json
            cypress/fixtures/missing_elements820.json
            cypress/fixtures/missing_elements821.json
            cypress/fixtures/missing_elements822.json
            cypress/fixtures/missing_elements823.json
            cypress/fixtures/missing_elements824.json
            cypress/fixtures/missing_elements825.json
            cypress/fixtures/missing_elements826.json
            cypress/fixtures/missing_elements827.json
            cypress/fixtures/missing_elements828.json
            cypress/fixtures/missing_elements829.json
            cypress/fixtures/missing_elements830.json
            cypress/fixtures/missing_elements831.json
            cypress/fixtures/missing_elements832.json
            cypress/fixtures/missing_elements833.json
            cypress/fixtures/missing_elements834.json
            cypress/fixtures/missing_elements835.json
            cypress/fixtures/missing_elements836.json
            cypress/fixtures/missing_elements837.json
            cypress/fixtures/missing_elements838.json
            cypress/fixtures/missing_elements839.json
            cypress/fixtures/missing_elements840.json
            cypress/fixtures/missing_elements841.json
            cypress/fixtures/missing_elements842.json
            cypress/fixtures/missing_elements843.json
            cypress/fixtures/missing_elements844.json
            cypress/fixtures/missing_elements845.json
            cypress/fixtures/missing_elements846.json
            cypress/fixtures/missing_elements847.json
            cypress/fixtures/missing_elements848.json
            cypress/fixtures/missing_elements849.json
            cypress/fixtures/missing_elements850.json
            cypress/fixtures/missing_elements851.json
            cypress/fixtures/missing_elements852.json
            cypress/fixtures/missing_elements853.json
            cypress/fixtures/missing_elements854.json
            cypress/fixtures/missing_elements855.json
            cypress/fixtures/missing_elements856.json
            cypress/fixtures/missing_elements857.json
            cypress/fixtures/missing_elements858.json
            cypress/fixtures/missing_elements859.json
            cypress/fixtures/missing_elements860.json
            cypress/fixtures/missing_elements861.json
            cypress/fixtures/missing_elements862.json
            cypress/fixtures/missing_elements863.json
            cypress/fixtures/missing_elements864.json
            cypress/fixtures/missing_elements865.json
            cypress/fixtures/missing_elements866.json
            cypress/fixtures/missing_elements867.json
            cypress/fixtures/missing_elements868.json
            cypress/fixtures/missing_elements869.json
            cypress/fixtures/missing_elements870.json
            cypress/fixtures/missing_elements871.json
            cypress/fixtures/missing_elements872.json
            cypress/fixtures/missing_elements873.json
            cypress/fixtures/missing_elements874.json
            cypress/fixtures/missing_elements875.json
            cypress/fixtures/missing_elements876.json
            cypress/fixtures/missing_elements877.json
            cypress/fixtures/missing_elements878.json
            cypress/fixtures/missing_elements879.json
            cypress/fixtures/missing_elements880.json
            cypress/fixtures/missing_elements881.json
            cypress/fixtures/missing_elements882.json
            cypress/fixtures/missing_elements883.json
            cypress/fixtures/missing_elements884.json
            cypress/fixtures/missing_elements885.json
            cypress/fixtures/missing_elements886.json
            cypress/fixtures/missing_elements887.json
            cypress/fixtures/missing_elements888.json
            cypress/fixtures/missing_elements889.json
            cypress/fixtures/missing_elements890.json
            cypress/fixtures/missing_elements891.json
            cypress/fixtures/missing_elements892.json
            cypress/fixtures/missing_elements893.json
            cypress/fixtures/missing_elements894.json
            cypress/fixtures/missing_elements895.json
            cypress/fixtures/missing_elements896.json
            cypress/fixtures/missing_elements897.json
            cypress/fixtures/missing_elements898.json
            cypress/fixtures/missing_elements899.json
            cypress/fixtures/missing_elements900.json
            cypress/fixtures/missing_elements901.json
            cypress/fixtures/missing_elements902.json
            cypress/fixtures/missing_elements903.json
            cypress/fixtures/missing_elements904.json
            cypress/fixtures/missing_elements905.json
            cypress/fixtures/missing_elements906.json
            cypress/fixtures/missing_elements907.json
            cypress/fixtures/missing_elements908.json
            cypress/fixtures/missing_elements909.json
            cypress/fixtures/missing_elements910.json
            cypress/fixtures/missing_elements911.json
            cypress/fixtures/missing_elements912.json
            cypress/fixtures/missing_elements913.json
            cypress/fixtures/missing_elements914.json
            cypress/fixtures/missing_elements915.json
            cypress/fixtures/missing_elements916.json
            cypress/fixtures/missing_elements917.json
            cypress/fixtures/missing_elements918.json
            cypress/fixtures/missing_elements919.json
            cypress/fixtures/missing_elements920.json
            cypress/fixtures/missing_elements921.json
            cypress/fixtures/missing_elements922.json
            cypress/fixtures/missing_elements923.json
            cypress/fixtures/missing_elements924.json
            cypress/fixtures/missing_elements925.json
            cypress/fixtures/missing_elements926.json
            cypress/fixtures/missing_elements927.json
            cypress/fixtures/missing_elements928.json
            cypress/fixtures/missing_elements929.json
            cypress/fixtures/missing_elements930.json
            cypress/fixtures/missing_elements931.json
            cypress/fixtures/missing_elements932.json
            cypress/fixtures/missing_elements933.json
            cypress/fixtures/missing_elements934.json
            cypress/fixtures/missing_elements935.json
            cypress/fixtures/missing_elements936.json
            cypress/fixtures/missing_elements937.json
            cypress/fixtures/missing_elements938.json
            cypress/fixtures/missing_elements939.json
            cypress/fixtures/missing_elements940.json
            cypress/fixtures/missing_elements941.json
            cypress/fixtures/missing_elements942.json
            cypress/fixtures/missing_elements943.json
            cypress/fixtures/missing_elements944.json
            cypress/fixtures/missing_elements945.json
            cypress/fixtures/missing_elements946.json
            cypress/fixtures/missing_elements947.json
            cypress/fixtures/missing_elements948.json
            cypress/fixtures/missing_elements949.json
            cypress/fixtures/missing_elements950.json
            cypress/fixtures/missing_elements951.json
            cypress/fixtures/missing_elements952.json
            cypress/fixtures/missing_elements953.json
            cypress/fixtures/missing_elements954.json
            cypress/fixtures/missing_elements955.json
            cypress/fixtures/missing_elements956.json
            cypress/fixtures/missing_elements957.json
            cypress/fixtures/missing_elements958.json
            cypress/fixtures/missing_elements959.json
            cypress/fixtures/missing_elements960.json
            cypress/fixtures/missing_elements961.json
            cypress/fixtures/missing_elements962.json
            cypress/fixtures/missing_elements963.json
            cypress/fixtures/missing_elements964.json
            cypress/fixtures/missing_elements965.json
            cypress/fixtures/missing_elements966.json
            cypress/fixtures/missing_elements967.json
            cypress/fixtures/missing_elements968.json
            cypress/fixtures/missing_elements969.json
            cypress/fixtures/missing_elements970.json
            cypress/fixtures/missing_elements971.json
            cypress/fixtures/missing_elements972.json
            cypress/fixtures/missing_elements973.json
            cypress/fixtures/missing_elements974.json
            cypress/fixtures/missing_elements975.json
            cypress/fixtures/missing_elements976.json
            cypress/fixtures/missing_elements977.json
            cypress/fixtures/missing_elements978.json
            cypress/fixtures/missing_elements979.json
            cypress/fixtures/missing_elements980.json
            cypress/fixtures/missing_elements981.json
            cypress/fixtures/missing_elements982.json
            cypress/fixtures/missing_elements983.json
            cypress/fixtures/missing_elements984.json
            cypress/fixtures/missing_elements985.json
            cypress/fixtures/missing_elements986.json
            cypress/fixtures/missing_elements987.json
            cypress/fixtures/missing_elements988.json
            cypress/fixtures/missing_elements989.json
            cypress/fixtures/missing_elements990.json
            cypress/fixtures/missing_elements991.json
            cypress/fixtures/missing_elements992.json
            cypress/fixtures/missing_elements993.json
            cypress/fixtures/missing_elements994.json
            cypress/fixtures/missing_elements995.json
            cypress/fixtures/missing_elements996.json
            cypress/fixtures/missing_elements997.json
            cypress/fixtures/missing_elements998.json
            cypress/fixtures/missing_elements999.json
            cypress/fixtures/missing_elements1000.json
            cypress/fixtures/missing_elements1001.json
            cypress/fixtures/missing_elements1002.json
